/**
 * /dante-design-an-interface executor — 3-parallel-agent design exploration.
 *
 * Deterministic mode produces 3 designs from caller-supplied prompts and
 * synthesizes a winner via a scored two-stage review. Hardware ceiling
 * enforced (max 3 parallel; refuses if more requested).
 */

import { createHash } from 'node:crypto';
import type { SkillExecutor } from '../runner.js';
import { HardwareCeilingError, assertHardwareCeiling } from '../../magic_skill_orchestration/index.js';

export interface DesignInputs {
  brief: string;
  hardConstraints: string[];
  successCriteria: string[];
  roles: string[];
  designs?: Record<string, { content: string; tradeoffsAccepted: string[] }>;
  /** Optional LLM caller. When provided AND `designs` is empty, generates 3 role-based drafts. */
  _llmCaller?: (prompt: string) => Promise<string>;
}

interface DesignReview {
  role: string;
  stageA: { specCompliance: 'pass' | 'fail'; missingConstraints: string[] };
  stageB: { qualityScore: number; rationale: string };
}

interface DesignOutput {
  selectedRole: string | null;
  selectionRationale: string;
  reviews: DesignReview[];
  diversityCheck: 'pass' | 'fail';
  finalArtifactHash: string | null;
  blockingIssues: string[];
}

function checkRoleCeiling(roles: string[]): string | null {
  try {
    assertHardwareCeiling('inferno', roles.length);
  } catch (err) {
    if (err instanceof HardwareCeilingError) return err.message;
    throw err;
  }
  if (roles.length < 1) return 'No roles specified — refusing to dispatch 0 parallel agents';
  return null;
}

async function generateRoleDesign(
  role: string,
  inputs: DesignInputs,
  llmCaller: (p: string) => Promise<string>
): Promise<{ content: string; tradeoffsAccepted: string[] } | null> {
  try {
    const prompt = [
      `You are a sub-agent assigned the role "${role}" producing a design draft.`,
      '',
      `Brief: ${inputs.brief}`,
      `Hard constraints: ${inputs.hardConstraints.join(', ')}`,
      `Success criteria: ${inputs.successCriteria.join(', ')}`,
      '',
      `Output the design as plain text (max 200 words). Then on a final line write:`,
      `TRADEOFFS: <comma-separated tradeoffs accepted by this role>`
    ].join('\n');
    const response = await llmCaller(prompt);
    const tradeoffMatch = /TRADEOFFS\s*:\s*([^\n]+)/i.exec(response);
    const tradeoffs = tradeoffMatch ? (tradeoffMatch[1] ?? '').split(/[,;]/).map(s => s.trim()).filter(Boolean) : [`generated by role: ${role}`];
    const content = response.replace(/TRADEOFFS\s*:\s*[^\n]+\n?/i, '').trim();
    return { content, tradeoffsAccepted: tradeoffs };
  } catch {
    return null;
  }
}

function buildReview(role: string, design: { content: string; tradeoffsAccepted: string[] }, inputs: DesignInputs): DesignReview {
  const missing = inputs.hardConstraints.filter(c => !design.content.toLowerCase().includes(c.toLowerCase()));
  const stageA: DesignReview['stageA'] = missing.length === 0
    ? { specCompliance: 'pass', missingConstraints: [] }
    : { specCompliance: 'fail', missingConstraints: missing };
  const qualityScore = stageA.specCompliance === 'pass' ? scoreQuality(design, inputs.successCriteria) : 0;
  return {
    role, stageA,
    stageB: {
      qualityScore,
      rationale: stageA.specCompliance === 'pass'
        ? `quality score ${qualityScore.toFixed(2)} based on success-criteria coverage and tradeoff explicitness`
        : `disqualified — missing constraints: ${missing.join(', ')}`
    }
  };
}

function selectWinner(
  reviews: DesignReview[],
  designs: Record<string, { content: string; tradeoffsAccepted: string[] }>,
  diversityCheck: 'pass' | 'fail'
): Awaited<ReturnType<SkillExecutor>> {
  const stageAPassed = reviews.filter(r => r.stageA.specCompliance === 'pass');
  if (stageAPassed.length === 0) {
    return blockingResult(['No design passed Stage A spec compliance — re-dispatch with refined brief']);
  }
  if (stageAPassed.length === 1) {
    const winner = stageAPassed[0]!;
    return wrapOutput({
      selectedRole: winner.role,
      selectionRationale: `Only design that passed Stage A spec compliance.`,
      reviews, diversityCheck,
      finalArtifactHash: hashOf(designs[winner.role]!.content),
      blockingIssues: []
    }, designs, reviews);
  }
  const sortedByScore = [...stageAPassed].sort((a, b) => b.stageB.qualityScore - a.stageB.qualityScore);
  const top = sortedByScore[0]!;
  const second = sortedByScore[1]!;
  if (Math.abs(top.stageB.qualityScore - second.stageB.qualityScore) < 0.01) {
    return blockingResult([`Tie between ${top.role} and ${second.role} on Stage B quality — escalate to founder rather than auto-tiebreak`]);
  }
  return wrapOutput({
    selectedRole: top.role,
    selectionRationale: `${top.role} scored ${top.stageB.qualityScore.toFixed(2)} vs runner-up ${second.role} at ${second.stageB.qualityScore.toFixed(2)}. Tradeoffs lost: ${designs[top.role]!.tradeoffsAccepted.join('; ')}.`,
    reviews, diversityCheck,
    finalArtifactHash: hashOf(designs[top.role]!.content),
    blockingIssues: []
  }, designs, reviews);
}

export const danteDesignAnInterfaceExecutor: SkillExecutor = async (raw) => {
  const inputs = parseInputs(raw);
  const ceilingError = checkRoleCeiling(inputs.roles);
  if (ceilingError) return blockingResult([ceilingError]);

  const designs: Record<string, { content: string; tradeoffsAccepted: string[] }> = inputs.designs ? { ...inputs.designs } : {};

  if (inputs._llmCaller) {
    for (const role of inputs.roles) {
      if (designs[role]) continue;
      const design = await generateRoleDesign(role, inputs, inputs._llmCaller);
      if (design) designs[role] = design;
    }
  }

  const blocking: string[] = [];
  for (const role of inputs.roles) {
    if (!designs[role]) blocking.push(`Role "${role}" produced no design (sub-agent failed or skipped)`);
  }
  if (blocking.length > 0) return blockingResult(blocking);

  const reviews: DesignReview[] = inputs.roles.map(role => buildReview(role, designs[role]!, inputs));
  const tradeoffSets = inputs.roles.map(r => new Set(designs[r]!.tradeoffsAccepted));
  const diversityCheck: 'pass' | 'fail' = tradeoffSets.every(s => setsEqual(s, tradeoffSets[0]!)) ? 'fail' : 'pass';

  return selectWinner(reviews, designs, diversityCheck);
};

function parseInputs(raw: Record<string, unknown>): DesignInputs {
  return {
    brief: typeof raw.brief === 'string' ? raw.brief : '',
    hardConstraints: Array.isArray(raw.hardConstraints) ? (raw.hardConstraints as string[]) : [],
    successCriteria: Array.isArray(raw.successCriteria) ? (raw.successCriteria as string[]) : [],
    roles: Array.isArray(raw.roles) ? (raw.roles as string[]) : [],
    designs: (typeof raw.designs === 'object' && raw.designs !== null
      ? raw.designs
      : undefined) as DesignInputs['designs'],
    _llmCaller: typeof raw._llmCaller === 'function' ? (raw._llmCaller as (p: string) => Promise<string>) : undefined
  };
}

function scoreQuality(design: { content: string; tradeoffsAccepted: string[] }, successCriteria: string[]): number {
  if (successCriteria.length === 0) return 7.0; // baseline when criteria not stated
  const hits = successCriteria.filter(c => design.content.toLowerCase().includes(c.toLowerCase())).length;
  const coverage = hits / successCriteria.length;
  const tradeoffBonus = Math.min(1, design.tradeoffsAccepted.length / 2);
  return Number((6.0 + coverage * 3.0 + tradeoffBonus).toFixed(2));
}

function setsEqual<T>(a: Set<T>, b: Set<T>): boolean {
  if (a.size !== b.size) return false;
  for (const v of a) if (!b.has(v)) return false;
  return true;
}

function hashOf(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

function blockingResult(blocking: string[]): Awaited<ReturnType<SkillExecutor>> {
  const output: DesignOutput = {
    selectedRole: null,
    selectionRationale: 'BLOCKED — see blockingIssues',
    reviews: [],
    diversityCheck: 'fail',
    finalArtifactHash: null,
    blockingIssues: blocking
  };
  return {
    output,
    phaseArtifacts: [{ label: 'phase_blocked', payload: blocking }],
    surfacedAssumptions: ['Design exploration blocked; founder must adjust brief or roles before retry.']
  };
}

function wrapOutput(output: DesignOutput, designs: Record<string, { content: string; tradeoffsAccepted: string[] }>, reviews: DesignReview[]): Awaited<ReturnType<SkillExecutor>> {
  return {
    output,
    phaseArtifacts: [
      { label: 'phase1_brief_parsed', payload: { selectedRole: output.selectedRole } },
      ...Object.entries(designs).map(([role, d]) => ({ label: `subagent_${role}_design`, payload: d })),
      { label: 'phase3_reviews', payload: reviews },
      { label: 'phase4_synthesis', payload: { selected: output.selectedRole, rationale: output.selectionRationale } }
    ],
    surfacedAssumptions: [
      `Selection assumes Stage B quality scoring weights success-criteria coverage equally with tradeoff explicitness; founder may override.`
    ]
  };
}
