// cli-stage2-pure.test.ts — pure exported function tests (no filesystem, no LLM, no network)
// Covers: formatCommandReference (docs.ts), resolveUpdateMcpMode (update-mcp.ts),
//         validateLiveReleaseConfig (doctor.ts)
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { formatCommandReference } from '../src/cli/commands/docs.js';
import { resolveUpdateMcpMode } from '../src/cli/commands/update-mcp.js';
import { validateLiveReleaseConfig } from '../src/cli/commands/doctor.js';

// ── formatCommandReference ────────────────────────────────────────────────────

describe('formatCommandReference', () => {
  it('returns a non-empty string', () => {
    const md = formatCommandReference();
    assert.ok(md.length > 100, 'should produce substantial markdown');
  });

  it('includes a Table of Contents section', () => {
    const md = formatCommandReference();
    assert.ok(md.includes('## Table of Contents'), 'should include Table of Contents');
  });

  it('includes all expected command groups', () => {
    const md = formatCommandReference();
    for (const group of ['Pipeline', 'Automation', 'Design', 'Intelligence', 'Tools', 'Meta']) {
      assert.ok(md.includes(`## ${group}`), `should include group: ${group}`);
    }
  });

  it('includes key canonical commands', () => {
    const md = formatCommandReference();
    const expectedCommands = ['init', 'specify', 'forge', 'verify', 'synthesize', 'magic', 'inferno', 'doctor', 'config'];
    for (const cmd of expectedCommands) {
      assert.ok(md.includes(`danteforge ${cmd}`), `should include command: ${cmd}`);
    }
  });

  it('auto-generated header references command count', () => {
    const md = formatCommandReference();
    assert.ok(md.includes('Auto-generated by `danteforge docs`'), 'should include auto-generated note');
  });

  it('each option is listed as a markdown list item', () => {
    const md = formatCommandReference();
    assert.ok(md.includes('- `--prompt`'), 'should include --prompt as option');
    assert.ok(md.includes('- `--light`'), 'should include --light as option');
  });

  it('returns same output on repeated calls (deterministic)', () => {
    const first = formatCommandReference();
    const second = formatCommandReference();
    assert.equal(first, second, 'should be deterministic');
  });
});

// ── resolveUpdateMcpMode ──────────────────────────────────────────────────────

describe('resolveUpdateMcpMode', () => {
  it('returns "check" when no flags set (default)', () => {
    assert.equal(resolveUpdateMcpMode({}), 'check');
  });

  it('returns "prompt" when prompt flag is set', () => {
    assert.equal(resolveUpdateMcpMode({ prompt: true }), 'prompt');
  });

  it('returns "apply" when apply flag is set', () => {
    assert.equal(resolveUpdateMcpMode({ apply: true }), 'apply');
  });

  it('returns "check" when check flag is set', () => {
    assert.equal(resolveUpdateMcpMode({ check: true }), 'check');
  });

  it('throws when prompt and apply are both set', () => {
    assert.throws(
      () => resolveUpdateMcpMode({ prompt: true, apply: true }),
      /mutually exclusive/i,
    );
  });

  it('throws when prompt and check are both set', () => {
    assert.throws(
      () => resolveUpdateMcpMode({ prompt: true, check: true }),
      /mutually exclusive/i,
    );
  });

  it('throws when apply and check are both set', () => {
    assert.throws(
      () => resolveUpdateMcpMode({ apply: true, check: true }),
      /mutually exclusive/i,
    );
  });
});

// ── validateLiveReleaseConfig ─────────────────────────────────────────────────

describe('validateLiveReleaseConfig', () => {
  it('returns error when DANTEFORGE_LIVE_PROVIDERS is not set', () => {
    const result = validateLiveReleaseConfig({});
    assert.ok(result.error, 'should return an error');
    assert.ok(result.error!.includes('DANTEFORGE_LIVE_PROVIDERS'), 'error should reference the env var');
    assert.deepEqual(result.providers, []);
  });

  it('returns error when DANTEFORGE_LIVE_PROVIDERS is empty string', () => {
    const result = validateLiveReleaseConfig({ DANTEFORGE_LIVE_PROVIDERS: '' });
    assert.ok(result.error, 'should return an error for empty string');
  });

  it('returns error when DANTEFORGE_LIVE_PROVIDERS is whitespace only', () => {
    const result = validateLiveReleaseConfig({ DANTEFORGE_LIVE_PROVIDERS: '   ' });
    assert.ok(result.error, 'should return error for whitespace-only value');
  });

  it('returns error when an unknown provider is listed', () => {
    const result = validateLiveReleaseConfig({ DANTEFORGE_LIVE_PROVIDERS: 'openai,unknown-provider' });
    assert.ok(result.error, 'should return error for unknown provider');
    assert.ok(result.error!.includes('unknown-provider'), 'error should name the bad provider');
  });

  it('deduplicates repeated provider names', () => {
    const result = validateLiveReleaseConfig({
      DANTEFORGE_LIVE_PROVIDERS: 'ollama,ollama',
      OLLAMA_MODEL: 'llama3',
    });
    assert.ok(!result.error, 'no error for valid (deduplicated) provider');
    assert.equal(result.providers.length, 1, 'should deduplicate to one provider');
    assert.equal(result.providers[0], 'ollama');
  });

  it('reports missing OPENAI_API_KEY when openai is in providers', () => {
    const result = validateLiveReleaseConfig({ DANTEFORGE_LIVE_PROVIDERS: 'openai' });
    assert.ok(!result.error, 'no config error');
    assert.ok(result.missing.some(m => m.includes('OPENAI_API_KEY')), 'should report missing OPENAI_API_KEY');
  });

  it('reports missing ANTHROPIC_API_KEY when claude is in providers', () => {
    const result = validateLiveReleaseConfig({ DANTEFORGE_LIVE_PROVIDERS: 'claude' });
    assert.ok(!result.error, 'no config error');
    assert.ok(result.missing.some(m => m.includes('ANTHROPIC_API_KEY')), 'should report missing ANTHROPIC_API_KEY');
  });

  it('reports missing XAI_API_KEY when grok is in providers', () => {
    const result = validateLiveReleaseConfig({ DANTEFORGE_LIVE_PROVIDERS: 'grok' });
    assert.ok(!result.error, 'no config error');
    assert.ok(result.missing.some(m => m.includes('XAI_API_KEY')), 'should report missing XAI_API_KEY');
  });

  it('reports missing OLLAMA_MODEL when ollama is in providers without model', () => {
    const result = validateLiveReleaseConfig({ DANTEFORGE_LIVE_PROVIDERS: 'ollama' });
    assert.ok(!result.error, 'no config error');
    assert.ok(result.missing.some(m => m.includes('OLLAMA_MODEL')), 'should report missing OLLAMA_MODEL');
  });

  it('returns empty missing array when all keys are present', () => {
    const result = validateLiveReleaseConfig({
      DANTEFORGE_LIVE_PROVIDERS: 'openai',
      OPENAI_API_KEY: 'sk-test-key',
    });
    assert.ok(!result.error, 'no config error');
    assert.deepEqual(result.missing, [], 'missing should be empty');
    assert.deepEqual(result.providers, ['openai']);
  });

  it('handles multiple valid providers correctly', () => {
    const result = validateLiveReleaseConfig({
      DANTEFORGE_LIVE_PROVIDERS: 'openai,claude',
      OPENAI_API_KEY: 'sk-openai-key',
      ANTHROPIC_API_KEY: 'sk-anthropic-key',
    });
    assert.ok(!result.error, 'no config error');
    assert.deepEqual(result.missing, [], 'should have no missing');
    assert.ok(result.providers.includes('openai'), 'should include openai');
    assert.ok(result.providers.includes('claude'), 'should include claude');
  });

  it('handles provider names case-insensitively', () => {
    const result = validateLiveReleaseConfig({
      DANTEFORGE_LIVE_PROVIDERS: 'OLLAMA',
      OLLAMA_MODEL: 'llama3',
    });
    assert.ok(!result.error, 'should accept uppercase provider names');
    assert.equal(result.providers[0], 'ollama', 'should normalize to lowercase');
  });
});
