import fs from 'fs/promises';
import path from 'path';

import type { DanteState } from './state.js';
import type { ScoreResult, ScoredArtifact } from './pdse.js';
import { SCORE_THRESHOLDS, ARTIFACT_COMMAND_MAP } from './pdse-config.js';
import type { CompletionTracker } from './completion-tracker.js';
import { isProtectedPath, requestSelfEditApproval, type SelfEditPolicy } from './safe-self-edit.js';
import type { AutoforgeGuidance, AutoforgeLoopContext, BlockingIssue } from './autoforge-loop.js';

const PIPELINE_STAGES = ['constitution', 'specify', 'clarify', 'tech-decide', 'plan', 'tasks', 'forge', 'verify', 'synthesize'];
const COMPLETION_THRESHOLD = 95;

export async function writeGuidanceFile(guidance: AutoforgeGuidance, cwd: string): Promise<void> {
  const content = formatGuidanceMarkdown(guidance);
  const filePath = path.join(cwd, '.danteforge', 'AUTOFORGE_GUIDANCE.md');
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content);
}

export function formatGuidanceMarkdown(guidance: AutoforgeGuidance): string {
  const lines: string[] = [
    '# Autoforge Guidance',
    '',
    `**Generated:** ${guidance.timestamp}`,
    `**Overall Completion:** ${guidance.overallCompletion}%`,
    `**Current Bottleneck:** ${guidance.currentBottleneck}`,
    `**Recommended Action:** \`${guidance.recommendedCommand}\``,
    `**Reason:** ${guidance.recommendedReason}`,
    `**Auto-Advance Eligible:** ${guidance.autoAdvanceEligible ? 'Yes' : 'No'}`,
  ];

  if (guidance.autoAdvanceBlockReason) {
    lines.push(`**Block Reason:** ${guidance.autoAdvanceBlockReason}`);
  }

  lines.push(`**Estimated Steps to Completion:** ${guidance.estimatedStepsToCompletion}`);
  lines.push('');

  if (guidance.blockingIssues.length > 0) {
    lines.push('## Blocking Issues');
    lines.push('');
    lines.push('| Artifact | Score | Decision | Remediation |');
    lines.push('|----------|-------|----------|-------------|');
    for (const issue of guidance.blockingIssues) {
      lines.push(`| ${issue.artifact} | ${issue.score} | ${issue.decision} | \`${issue.remediation}\` |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by DanteForge Autoforge v2 IAL*');

  return lines.join('\n');
}

export function findBlockedArtifacts(scores: Record<ScoredArtifact, ScoreResult>): BlockingIssue[] {
  const blocked: BlockingIssue[] = [];
  for (const [name, result] of Object.entries(scores)) {
    if (result.score < SCORE_THRESHOLDS.NEEDS_WORK) {
      const command = ARTIFACT_COMMAND_MAP[name as ScoredArtifact] ?? name.toLowerCase();
      blocked.push({
        artifact: name,
        score: result.score,
        decision: result.autoforgeDecision,
        remediation: `danteforge ${command} --refine`,
      });
    }
  }
  return blocked;
}

export function determineNextCommand(
  state: DanteState,
  tracker: CompletionTracker,
  scores: Record<ScoredArtifact, ScoreResult>,
): string | null {
  const currentStage = state.workflowStage;
  const pipelineOnlyStages = new Set(['synthesize', 'verify', 'forge', 'ux-refine']);
  const planningBlockedByStage = pipelineOnlyStages.has(currentStage ?? '');

  if (!tracker.phases.planning.complete && !planningBlockedByStage) {
    for (const artifact of ['CONSTITUTION', 'SPEC', 'CLARIFY', 'PLAN', 'TASKS'] as ScoredArtifact[]) {
      const score = scores[artifact];
      if (score.score < SCORE_THRESHOLDS.ACCEPTABLE) {
        return ARTIFACT_COMMAND_MAP[artifact];
      }
    }
  }

  if (!tracker.phases.execution.complete) {
    const forgePrerequisiteStages = new Set(['tasks', 'design', 'forge', 'ux-refine', 'verify', 'synthesize']);
    if (!forgePrerequisiteStages.has(currentStage ?? '')) return 'tasks';
    return 'forge';
  }

  if (!tracker.phases.verification.complete) return 'verify';
  if (!tracker.phases.synthesis.complete) return 'synthesize';
  if (!tracker.phases.planning.complete && planningBlockedByStage) return 'forge';
  return null;
}

export function computeEstimatedSteps(ctx: AutoforgeLoopContext): number {
  const tracker = ctx.state.completionTracker;
  if (!tracker) return PIPELINE_STAGES.length;

  let steps = 0;
  if (!tracker.phases.planning.complete) {
    steps += Object.values(tracker.phases.planning.artifacts).filter(a => !a.complete).length;
  }
  if (!tracker.phases.execution.complete) {
    steps += tracker.phases.execution.totalWaves - tracker.phases.execution.wavesComplete;
  }
  if (!tracker.phases.verification.complete) steps += 1;
  if (!tracker.phases.synthesis.complete) steps += 1;
  return Math.max(1, steps);
}

export function buildGuidance(
  tracker: CompletionTracker,
  scores: Record<ScoredArtifact, ScoreResult>,
  ctx: AutoforgeLoopContext,
): AutoforgeGuidance {
  const blockingIssues = findBlockedArtifacts(scores);
  const bottleneck = findBottleneck(tracker, scores);
  const nextCommand = determineNextCommand(ctx.state, tracker, scores) ?? 'ship --dry-run';
  const autoAdvanceEligible = blockingIssues.length === 0 && tracker.overall < COMPLETION_THRESHOLD;

  return {
    timestamp: new Date().toISOString(),
    overallCompletion: tracker.overall,
    currentBottleneck: bottleneck,
    blockingIssues,
    recommendedCommand: `danteforge ${nextCommand}`,
    recommendedReason: getRecommendationReason(tracker, blockingIssues),
    autoAdvanceEligible,
    autoAdvanceBlockReason: !autoAdvanceEligible && blockingIssues.length > 0
      ? `${blockingIssues.length} artifact(s) below score threshold`
      : undefined,
    estimatedStepsToCompletion: computeEstimatedSteps(ctx),
  };
}

export function findBottleneck(
  tracker: CompletionTracker,
  scores: Record<ScoredArtifact, ScoreResult>,
): string {
  let lowestArtifact = '';
  let lowestScore = Infinity;
  for (const [name, result] of Object.entries(scores)) {
    if (result.score < lowestScore) {
      lowestScore = result.score;
      lowestArtifact = name;
    }
  }

  if (lowestScore < SCORE_THRESHOLDS.NEEDS_WORK) {
    return `${lowestArtifact} (score: ${lowestScore}, blocked)`;
  }
  if (!tracker.phases.planning.complete) return 'Planning phase incomplete';
  if (!tracker.phases.execution.complete) return 'Execution phase incomplete';
  if (!tracker.phases.verification.complete) return 'Verification phase incomplete';
  if (!tracker.phases.synthesis.complete) return 'Synthesis phase incomplete';
  return 'None';
}

export interface CheckProtectedTaskPathsOpts {
  cwd?: string;
  _requestApproval?: typeof requestSelfEditApproval;
}

export async function checkProtectedTaskPaths(
  state: DanteState,
  opts: CheckProtectedTaskPathsOpts = {},
): Promise<{ blocked: string[]; approved: boolean }> {
  const { cwd, _requestApproval = requestSelfEditApproval } = opts;
  const policy: SelfEditPolicy = state.selfEditPolicy ?? 'deny';
  const phaseTasks = state.tasks[state.currentPhase ?? 1] ?? [];
  const blocked: string[] = [];

  for (const task of phaseTasks) {
    for (const file of task.files ?? []) {
      if (!isProtectedPath(file)) continue;
      const approved = await _requestApproval(file, task.name, { cwd, policy });
      if (!approved) blocked.push(file);
    }
  }

  return { blocked, approved: blocked.length === 0 };
}

export function getRecommendationReason(
  tracker: CompletionTracker,
  blockingIssues: BlockingIssue[],
): string {
  if (blockingIssues.length > 0) {
    return `${blockingIssues.length} artifact(s) need remediation before advancement`;
  }
  if (!tracker.phases.planning.complete) return 'Complete planning artifacts to advance';
  if (!tracker.phases.execution.complete) return 'Execute remaining forge waves';
  if (!tracker.phases.verification.complete) return 'Run verification checks';
  if (!tracker.phases.synthesis.complete) return 'Generate synthesis report';
  return 'Project ready for ship';
}
