// competitor-baselines.ts — Hardcoded competitor profiles for each project preset.
// Split from competitor-scanner.ts to keep files under the 750-LOC hard cap.
import type { CompetitorProfile } from './competitor-scanner.js';

// -- Preset baselines --------------------------------------------------------
// Each baseline corresponds to a named preset in src/core/peer-presets.ts.
// `scanCompetitors` picks the right baseline based on resolved project
// identity, so DanteForge (dev-tool-optimizer preset) sees its spec-kit /
// BMAD / etc. peers, while DanteCode (coding-assistant preset) sees the
// Cursor / Aider / OpenHands / etc. peers.

const DEV_TOOL_OPTIMIZER_BASELINES: CompetitorProfile[] = [
  // -- Direct peers: spec-driven dev kits --------------------------------------
  {
    name: 'spec-kit (GitHub)',
    url: 'https://github.com/github/spec-kit',
    description: 'GitHub\'s official spec-driven development kit. Constitution + spec + plan + tasks flow for AI agents.',
    source: 'hardcoded',
    scores: {
      functionality: 72, testing: 60, errorHandling: 60, security: 70,
      uxPolish: 72, documentation: 80, performance: 65, maintainability: 75,
      developerExperience: 80, autonomy: 55, planningQuality: 85, selfImprovement: 50,
      specDrivenPipeline: 92, convergenceSelfHealing: 35, tokenEconomy: 50,
      ecosystemMcp: 60, enterpriseReadiness: 75, communityAdoption: 82,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'BMad-METHOD',
    url: 'https://github.com/bmadcode/BMAD-METHOD',
    description: 'Multi-agent spec workflow (analyst, PM, architect, dev, QA, scrum master). Document sharding and agent role discipline.',
    source: 'hardcoded',
    scores: {
      functionality: 70, testing: 55, errorHandling: 55, security: 60,
      uxPolish: 60, documentation: 78, performance: 60, maintainability: 70,
      developerExperience: 72, autonomy: 70, planningQuality: 88, selfImprovement: 55,
      specDrivenPipeline: 90, convergenceSelfHealing: 40, tokenEconomy: 55,
      ecosystemMcp: 55, enterpriseReadiness: 55, communityAdoption: 70,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'OpenSpec',
    url: 'https://github.com/Fission-AI/OpenSpec',
    description: 'Spec-first workflow for AI coding assistants. Lightweight constitution + change-request format.',
    source: 'hardcoded',
    scores: {
      functionality: 60, testing: 50, errorHandling: 50, security: 55,
      uxPolish: 60, documentation: 68, performance: 55, maintainability: 65,
      developerExperience: 65, autonomy: 50, planningQuality: 75, selfImprovement: 40,
      specDrivenPipeline: 80, convergenceSelfHealing: 30, tokenEconomy: 50,
      ecosystemMcp: 45, enterpriseReadiness: 40, communityAdoption: 55,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  // -- Direct peers: Claude Code / agent skill consolidators -------------------
  {
    name: 'anthropics/claude-skills',
    url: 'https://github.com/anthropics/claude-skills',
    description: 'Anthropic\'s official catalog of Claude Code Skills. Reference for skill structure, frontmatter conventions, dispatch model.',
    source: 'hardcoded',
    scores: {
      functionality: 70, testing: 55, errorHandling: 55, security: 75,
      uxPolish: 70, documentation: 82, performance: 60, maintainability: 75,
      developerExperience: 78, autonomy: 50, planningQuality: 60, selfImprovement: 45,
      specDrivenPipeline: 45, convergenceSelfHealing: 30, tokenEconomy: 55,
      ecosystemMcp: 85, enterpriseReadiness: 70, communityAdoption: 80,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'awesome-claude-code-skills',
    url: 'https://github.com/topics/claude-skills',
    description: 'Community aggregator of Claude Code Skills. Discoverability and breadth-of-coverage benchmark for skill catalogs.',
    source: 'hardcoded',
    scores: {
      functionality: 55, testing: 40, errorHandling: 40, security: 50,
      uxPolish: 55, documentation: 65, performance: 50, maintainability: 50,
      developerExperience: 68, autonomy: 35, planningQuality: 45, selfImprovement: 35,
      specDrivenPipeline: 30, convergenceSelfHealing: 25, tokenEconomy: 45,
      ecosystemMcp: 70, enterpriseReadiness: 35, communityAdoption: 75,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'cursor.directory',
    url: 'https://cursor.directory',
    description: 'Marketplace of Cursor rules and MCP servers. Skill marketplace benchmark for community adoption.',
    source: 'hardcoded',
    scores: {
      functionality: 55, testing: 35, errorHandling: 40, security: 55,
      uxPolish: 78, documentation: 60, performance: 60, maintainability: 55,
      developerExperience: 75, autonomy: 30, planningQuality: 40, selfImprovement: 30,
      specDrivenPipeline: 25, convergenceSelfHealing: 25, tokenEconomy: 45,
      ecosystemMcp: 70, enterpriseReadiness: 45, communityAdoption: 85,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  // -- Direct peers: autonomous research / improvement loops -------------------
  {
    name: 'Karpathy autoresearch',
    url: 'https://x.com/karpathy/status/autoresearch',
    description: 'Karpathy-style autonomous metric-driven optimization loop. Baseline -> experiment -> evaluate -> keep winner. DanteForge\'s self-improve loop heritage.',
    source: 'hardcoded',
    scores: {
      functionality: 65, testing: 55, errorHandling: 55, security: 50,
      uxPolish: 50, documentation: 55, performance: 65, maintainability: 60,
      developerExperience: 60, autonomy: 88, planningQuality: 65, selfImprovement: 90,
      specDrivenPipeline: 35, convergenceSelfHealing: 80, tokenEconomy: 55,
      ecosystemMcp: 35, enterpriseReadiness: 30, communityAdoption: 60,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'DSPy (Stanford)',
    url: 'https://github.com/stanfordnlp/dspy',
    description: 'Programming framework for compiling LLM pipelines: declarative modules + bootstrap-from-data optimizers (BootstrapFewShot, MIPRO).',
    source: 'hardcoded',
    scores: {
      functionality: 75, testing: 70, errorHandling: 65, security: 60,
      uxPolish: 55, documentation: 72, performance: 72, maintainability: 75,
      developerExperience: 68, autonomy: 70, planningQuality: 70, selfImprovement: 85,
      specDrivenPipeline: 50, convergenceSelfHealing: 65, tokenEconomy: 75,
      ecosystemMcp: 50, enterpriseReadiness: 55, communityAdoption: 78,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  // -- Pattern donors: orchestration peers -------------------------------------
  {
    name: 'MetaGPT',
    url: 'https://github.com/geekan/MetaGPT',
    description: 'Multi-agent framework assigning GPT roles (PM, architect, engineer, QA). SOP-driven planning.',
    source: 'hardcoded',
    scores: {
      functionality: 75, testing: 70, errorHandling: 65, security: 60,
      uxPolish: 55, documentation: 72, performance: 62, maintainability: 65,
      developerExperience: 65, autonomy: 75, planningQuality: 85, selfImprovement: 65,
      specDrivenPipeline: 75, convergenceSelfHealing: 60, tokenEconomy: 45,
      ecosystemMcp: 40, enterpriseReadiness: 35, communityAdoption: 72,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'CrewAI',
    url: 'https://github.com/joaomdmoura/crewai',
    description: 'Role-based multi-agent orchestration with crew/task primitives. Process modes (sequential, hierarchical).',
    source: 'hardcoded',
    scores: {
      functionality: 80, testing: 72, errorHandling: 74, security: 68,
      uxPolish: 65, documentation: 75, performance: 72, maintainability: 74,
      developerExperience: 72, autonomy: 82, planningQuality: 80, selfImprovement: 68,
      specDrivenPipeline: 55, convergenceSelfHealing: 60, tokenEconomy: 40,
      ecosystemMcp: 50, enterpriseReadiness: 42, communityAdoption: 70,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'AutoGen (Microsoft)',
    url: 'https://github.com/microsoft/autogen',
    description: 'Multi-agent conversation framework with dynamic collaboration, code-execution agents, group chat.',
    source: 'hardcoded',
    scores: {
      functionality: 82, testing: 75, errorHandling: 78, security: 72,
      uxPolish: 55, documentation: 78, performance: 76, maintainability: 78,
      developerExperience: 68, autonomy: 85, planningQuality: 78, selfImprovement: 65,
      specDrivenPipeline: 50, convergenceSelfHealing: 65, tokenEconomy: 45,
      ecosystemMcp: 55, enterpriseReadiness: 55, communityAdoption: 78,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'GPT-Engineer',
    url: 'https://github.com/gpt-engineer-org/gpt-engineer',
    description: 'Specify what to build, AI generates codebase from scratch. Early spec-to-code pioneer.',
    source: 'hardcoded',
    scores: {
      functionality: 70, testing: 55, errorHandling: 55, security: 55,
      uxPolish: 58, documentation: 68, performance: 58, maintainability: 60,
      developerExperience: 68, autonomy: 65, planningQuality: 70, selfImprovement: 45,
      specDrivenPipeline: 50, convergenceSelfHealing: 45, tokenEconomy: 35,
      ecosystemMcp: 40, enterpriseReadiness: 30, communityAdoption: 55,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'OpenHands (All-Hands AI)',
    url: 'https://github.com/All-Hands-AI/OpenHands',
    description: 'SWE-bench-leading autonomous agent with Docker-sandboxed execution environment. Forge-loop peer.',
    source: 'hardcoded',
    scores: {
      functionality: 85, testing: 80, errorHandling: 78, security: 80,
      uxPolish: 62, documentation: 72, performance: 74, maintainability: 72,
      developerExperience: 68, autonomy: 88, planningQuality: 72, selfImprovement: 65,
      specDrivenPipeline: 40, convergenceSelfHealing: 80, tokenEconomy: 45,
      ecosystemMcp: 55, enterpriseReadiness: 50, communityAdoption: 75,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Aider',
    url: 'https://aider.chat',
    description: 'Repo-map-aware terminal pair programmer. Inner-loop forge peer; git-commit-per-change discipline.',
    source: 'hardcoded',
    scores: {
      functionality: 78, testing: 68, errorHandling: 65, security: 62,
      uxPolish: 58, documentation: 70, performance: 65, maintainability: 70,
      developerExperience: 75, autonomy: 70, planningQuality: 60, selfImprovement: 55,
      specDrivenPipeline: 30, convergenceSelfHealing: 50, tokenEconomy: 55,
      ecosystemMcp: 40, enterpriseReadiness: 35, communityAdoption: 82,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'SWE-Agent (Princeton)',
    url: 'https://swe-agent.com',
    description: 'Autonomous agent for GitHub issues with custom ACI interface. SWE-bench heritage.',
    source: 'hardcoded',
    scores: {
      functionality: 80, testing: 78, errorHandling: 72, security: 65,
      uxPolish: 52, documentation: 68, performance: 68, maintainability: 68,
      developerExperience: 62, autonomy: 82, planningQuality: 72, selfImprovement: 58,
      specDrivenPipeline: 45, convergenceSelfHealing: 70, tokenEconomy: 40,
      ecosystemMcp: 35, enterpriseReadiness: 40, communityAdoption: 68,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'LangChain Agents',
    url: 'https://github.com/langchain-ai/langchain',
    description: 'Composable agent framework with 100+ tool integrations and ReAct reasoning pattern.',
    source: 'hardcoded',
    scores: {
      functionality: 82, testing: 72, errorHandling: 76, security: 70,
      uxPolish: 60, documentation: 80, performance: 70, maintainability: 68,
      developerExperience: 72, autonomy: 78, planningQuality: 72, selfImprovement: 65,
      specDrivenPipeline: 40, convergenceSelfHealing: 55, tokenEconomy: 50,
      ecosystemMcp: 88, enterpriseReadiness: 50, communityAdoption: 88,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
];

// -- Coding-assistant baseline -----------------------------------------------
// AI coding assistants and inner-loop dev agents. Used by sibling projects
// like DanteCode that directly compete with Cursor / Cline / Aider / etc.
// (NOT DanteForge — DanteForge sits on top of these as an optimizer.)

const CODING_ASSISTANT_BASELINES: CompetitorProfile[] = [
  {
    name: 'Cursor',
    url: 'https://cursor.com',
    description: 'AI-first code editor with deep codebase context and inline code generation.',
    source: 'hardcoded',
    scores: {
      functionality: 85, testing: 70, errorHandling: 68, security: 72,
      uxPolish: 92, documentation: 72, performance: 74, maintainability: 76,
      developerExperience: 90, autonomy: 65, planningQuality: 62, selfImprovement: 50,
      specDrivenPipeline: 35, convergenceSelfHealing: 40, tokenEconomy: 70,
      ecosystemMcp: 65, enterpriseReadiness: 60, communityAdoption: 95,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'GitHub Copilot Workspace',
    url: 'https://githubnext.com/projects/copilot-workspace',
    description: 'Task-centric dev environment. Brainstorm, plan, build, test in Copilot chat.',
    source: 'hardcoded',
    scores: {
      functionality: 82, testing: 78, errorHandling: 72, security: 80,
      uxPolish: 85, documentation: 75, performance: 70, maintainability: 74,
      developerExperience: 88, autonomy: 68, planningQuality: 76, selfImprovement: 55,
      specDrivenPipeline: 60, convergenceSelfHealing: 55, tokenEconomy: 55,
      ecosystemMcp: 80, enterpriseReadiness: 88, communityAdoption: 92,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Claude Code',
    url: 'https://claude.ai/code',
    description: 'Anthropic\'s official CLI for Claude. Agentic coding in the terminal.',
    source: 'hardcoded',
    scores: {
      functionality: 85, testing: 75, errorHandling: 78, security: 80,
      uxPolish: 72, documentation: 80, performance: 76, maintainability: 80,
      developerExperience: 88, autonomy: 72, planningQuality: 70, selfImprovement: 60,
      specDrivenPipeline: 40, convergenceSelfHealing: 55, tokenEconomy: 75,
      ecosystemMcp: 90, enterpriseReadiness: 72, communityAdoption: 90,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Devin (Cognition AI)',
    url: 'https://cognition.ai',
    description: 'Fully autonomous AI software engineer. First agent to exceed 13% on SWE-bench.',
    source: 'hardcoded',
    scores: {
      functionality: 88, testing: 72, errorHandling: 75, security: 70,
      uxPolish: 65, documentation: 68, performance: 72, maintainability: 70,
      developerExperience: 75, autonomy: 92, planningQuality: 78, selfImprovement: 60,
      specDrivenPipeline: 55, convergenceSelfHealing: 85, tokenEconomy: 50,
      ecosystemMcp: 45, enterpriseReadiness: 55, communityAdoption: 72,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Aider',
    url: 'https://aider.chat',
    description: 'AI pair programming in your terminal. Edits code across entire repos.',
    source: 'hardcoded',
    scores: {
      functionality: 78, testing: 68, errorHandling: 65, security: 62,
      uxPolish: 58, documentation: 70, performance: 65, maintainability: 70,
      developerExperience: 75, autonomy: 70, planningQuality: 60, selfImprovement: 55,
      specDrivenPipeline: 30, convergenceSelfHealing: 50, tokenEconomy: 55,
      ecosystemMcp: 40, enterpriseReadiness: 35, communityAdoption: 82,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'OpenHands (All-Hands AI)',
    url: 'https://github.com/All-Hands-AI/OpenHands',
    description: 'SWE-bench leading autonomous agent with Docker-sandboxed execution environment.',
    source: 'hardcoded',
    scores: {
      functionality: 85, testing: 80, errorHandling: 78, security: 80,
      uxPolish: 62, documentation: 72, performance: 74, maintainability: 72,
      developerExperience: 68, autonomy: 88, planningQuality: 72, selfImprovement: 65,
      specDrivenPipeline: 40, convergenceSelfHealing: 80, tokenEconomy: 45,
      ecosystemMcp: 55, enterpriseReadiness: 50, communityAdoption: 75,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Cline',
    url: 'https://github.com/cline/cline',
    description: 'Autonomous VS Code agent that reads, writes, and executes code with human approval gates.',
    source: 'hardcoded',
    scores: {
      functionality: 80, testing: 68, errorHandling: 72, security: 72,
      uxPolish: 85, documentation: 65, performance: 72, maintainability: 68,
      developerExperience: 88, autonomy: 78, planningQuality: 60, selfImprovement: 55,
      specDrivenPipeline: 25, convergenceSelfHealing: 45, tokenEconomy: 55,
      ecosystemMcp: 85, enterpriseReadiness: 50, communityAdoption: 78,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Continue.dev',
    url: 'https://docs.continue.dev',
    description: 'Open-source IDE copilot with agent, chat, autocomplete, and edit modes across IDEs.',
    source: 'hardcoded',
    scores: {
      functionality: 80, testing: 70, errorHandling: 70, security: 72,
      uxPolish: 88, documentation: 75, performance: 74, maintainability: 72,
      developerExperience: 90, autonomy: 65, planningQuality: 62, selfImprovement: 58,
      specDrivenPipeline: 30, convergenceSelfHealing: 40, tokenEconomy: 50,
      ecosystemMcp: 82, enterpriseReadiness: 48, communityAdoption: 75,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Codex CLI (OpenAI)',
    url: 'https://developers.openai.com/codex/cli',
    description: 'Rust-based terminal agent with OS-level sandboxing, first-class plugins, MCP support.',
    source: 'hardcoded',
    scores: {
      functionality: 82, testing: 72, errorHandling: 72, security: 78,
      uxPolish: 70, documentation: 75, performance: 80, maintainability: 76,
      developerExperience: 82, autonomy: 80, planningQuality: 68, selfImprovement: 55,
      specDrivenPipeline: 35, convergenceSelfHealing: 60, tokenEconomy: 65,
      ecosystemMcp: 78, enterpriseReadiness: 65, communityAdoption: 80,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Gemini CLI (Google)',
    url: 'https://github.com/google-gemini/gemini-cli',
    description: 'Open-source CLI with 1M token context via Gemini 2.5 Pro, generous free tier.',
    source: 'hardcoded',
    scores: {
      functionality: 78, testing: 68, errorHandling: 68, security: 72,
      uxPolish: 72, documentation: 70, performance: 72, maintainability: 70,
      developerExperience: 78, autonomy: 65, planningQuality: 60, selfImprovement: 50,
      specDrivenPipeline: 25, convergenceSelfHealing: 40, tokenEconomy: 72,
      ecosystemMcp: 65, enterpriseReadiness: 68, communityAdoption: 75,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'GitHub Copilot CLI',
    url: 'https://github.blog/changelog/2026-02-25-github-copilot-cli-is-now-generally-available/',
    description: 'GA Feb 2026. Plan mode, autopilot, dynamic agent delegation, multi-model, persistent memory.',
    source: 'hardcoded',
    scores: {
      functionality: 85, testing: 78, errorHandling: 75, security: 82,
      uxPolish: 85, documentation: 80, performance: 74, maintainability: 78,
      developerExperience: 90, autonomy: 75, planningQuality: 78, selfImprovement: 60,
      specDrivenPipeline: 55, convergenceSelfHealing: 60, tokenEconomy: 60,
      ecosystemMcp: 82, enterpriseReadiness: 88, communityAdoption: 95,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Goose (Block)',
    url: 'https://block.xyz/open-source/goose',
    description: 'Open-source MCP-native agent, Linux Foundation Agentic AI member, red-team tested.',
    source: 'hardcoded',
    scores: {
      functionality: 78, testing: 70, errorHandling: 72, security: 75,
      uxPolish: 68, documentation: 70, performance: 68, maintainability: 72,
      developerExperience: 75, autonomy: 72, planningQuality: 60, selfImprovement: 55,
      specDrivenPipeline: 30, convergenceSelfHealing: 50, tokenEconomy: 50,
      ecosystemMcp: 85, enterpriseReadiness: 55, communityAdoption: 72,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Replit Agent',
    url: 'https://replit.com',
    description: 'Most autonomous app builder — continuous generate/test/debug/fix loop with deployment.',
    source: 'hardcoded',
    scores: {
      functionality: 82, testing: 68, errorHandling: 70, security: 68,
      uxPolish: 88, documentation: 65, performance: 70, maintainability: 65,
      developerExperience: 88, autonomy: 85, planningQuality: 65, selfImprovement: 60,
      specDrivenPipeline: 45, convergenceSelfHealing: 78, tokenEconomy: 55,
      ecosystemMcp: 60, enterpriseReadiness: 50, communityAdoption: 85,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'SWE-Agent (Princeton)',
    url: 'https://swe-agent.com',
    description: 'Autonomous agent for GitHub issues. ACI interface for OS interaction.',
    source: 'hardcoded',
    scores: {
      functionality: 80, testing: 78, errorHandling: 72, security: 65,
      uxPolish: 52, documentation: 68, performance: 68, maintainability: 68,
      developerExperience: 62, autonomy: 82, planningQuality: 72, selfImprovement: 58,
      specDrivenPipeline: 45, convergenceSelfHealing: 70, tokenEconomy: 40,
      ecosystemMcp: 35, enterpriseReadiness: 40, communityAdoption: 68,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'CodiumAI / Qodo',
    url: 'https://www.codium.ai',
    description: 'AI test suite generation and code integrity analysis directly from source code.',
    source: 'hardcoded',
    scores: {
      functionality: 80, testing: 90, errorHandling: 72, security: 70,
      uxPolish: 78, documentation: 68, performance: 68, maintainability: 74,
      developerExperience: 82, autonomy: 68, planningQuality: 60, selfImprovement: 72,
      specDrivenPipeline: 30, convergenceSelfHealing: 72, tokenEconomy: 50,
      ecosystemMcp: 60, enterpriseReadiness: 65, communityAdoption: 70,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'CodeRabbit',
    url: 'https://coderabbit.ai',
    description: 'AI-powered code review with line-level suggestions and context-aware PR feedback.',
    source: 'hardcoded',
    scores: {
      functionality: 82, testing: 78, errorHandling: 80, security: 82,
      uxPolish: 85, documentation: 72, performance: 72, maintainability: 80,
      developerExperience: 88, autonomy: 62, planningQuality: 60, selfImprovement: 68,
      specDrivenPipeline: 25, convergenceSelfHealing: 50, tokenEconomy: 45,
      ecosystemMcp: 70, enterpriseReadiness: 78, communityAdoption: 72,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Kiro (AWS)',
    url: 'https://kiro.dev',
    description: 'Spec-driven development tool with EARS-notation requirements, agent hooks, built on Bedrock.',
    source: 'hardcoded',
    scores: {
      functionality: 78, testing: 72, errorHandling: 70, security: 78,
      uxPolish: 75, documentation: 72, performance: 70, maintainability: 72,
      developerExperience: 80, autonomy: 72, planningQuality: 82, selfImprovement: 55,
      specDrivenPipeline: 80, convergenceSelfHealing: 55, tokenEconomy: 60,
      ecosystemMcp: 65, enterpriseReadiness: 80, communityAdoption: 62,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
  {
    name: 'Kilo Code',
    url: 'https://marketplace.visualstudio.com/items?itemName=kilocode.Kilo-Code',
    description: 'Open-source multi-IDE agent with structured modes, 500+ AI model support.',
    source: 'hardcoded',
    scores: {
      functionality: 78, testing: 68, errorHandling: 68, security: 70,
      uxPolish: 82, documentation: 68, performance: 72, maintainability: 70,
      developerExperience: 85, autonomy: 72, planningQuality: 58, selfImprovement: 52,
      specDrivenPipeline: 30, convergenceSelfHealing: 45, tokenEconomy: 55,
      ecosystemMcp: 78, enterpriseReadiness: 48, communityAdoption: 62,
      contextEconomy: 0, causalCoherence: 0,
    },
  },
];


export { DEV_TOOL_OPTIMIZER_BASELINES, CODING_ASSISTANT_BASELINES };
export { DEV_TOOL_OPTIMIZER_BASELINES as COMPETITOR_BASELINES };
export { DEV_TOOL_OPTIMIZER_BASELINES as DEV_TOOL_BASELINES };
