// context-syncer.ts — Syncs project context to IDE/agent config files
import path from 'path';
import { estimateTokens } from './token-estimator.js';
import type { DanteState } from './state.js';

export type ContextTarget = 'cursor' | 'claude' | 'codex' | 'all';

export interface SyncedContextFile {
  target: ContextTarget;
  path: string;
  content: string;
  tokensEstimated: number;
}

export interface ContextSyncResult {
  synced: SyncedContextFile[];
  skipped: string[];
  totalTokens: number;
}

export interface ContextSyncOptions {
  target?: ContextTarget;          // default: 'all'
  cwd?: string;
  _readFile?: (p: string) => Promise<string>;
  _writeFile?: (p: string, content: string) => Promise<void>;
  _mkdir?: (p: string, opts?: { recursive?: boolean }) => Promise<void>;
  _exists?: (p: string) => Promise<boolean>;
  _loadState?: (opts: { cwd?: string }) => Promise<DanteState>;
}

const DEFAULT_STATE: DanteState = {
  project: 'unknown',
  currentPhase: 1,
  workflowStage: 'tasks',
  tasks: {},
  auditLog: [],
  profile: '',
  lastHandoff: '',
};

function getTop5ConstitutionLines(constitution: string): string {
  return constitution
    .split('\n')
    .filter((l) => l.trimStart().startsWith('-') || l.trimStart().startsWith('#'))
    .slice(0, 5)
    .join('\n');
}

function formatActiveTasks(
  state: DanteState,
  limit: number,
): string {
  const phaseTasks = state.tasks[state.currentPhase];
  if (!phaseTasks || phaseTasks.length === 0) return 'No active tasks';
  return phaseTasks
    .slice(0, limit)
    .map((t) => `- ${t.name}`)
    .join('\n');
}

async function loadStateWith(
  cwd: string,
  opts: ContextSyncOptions,
): Promise<DanteState> {
  try {
    if (opts._loadState) {
      return await opts._loadState({ cwd });
    }
    const { loadState } = await import('./state.js');
    return await loadState({ cwd });
  } catch {
    return { ...DEFAULT_STATE };
  }
}

async function readConstitutionWith(
  cwd: string,
  opts: ContextSyncOptions,
): Promise<string> {
  const constitutionPath = path.join(cwd, '.danteforge', 'CONSTITUTION.md');
  try {
    if (opts._readFile) {
      return await opts._readFile(constitutionPath);
    }
    const { readFile } = await import('fs/promises');
    return await readFile(constitutionPath, 'utf8');
  } catch {
    return '';
  }
}

// ── Build helpers ─────────────────────────────────────────────────────────────

export async function buildCursorContext(
  cwd: string,
  opts: ContextSyncOptions,
): Promise<string> {
  const state = await loadStateWith(cwd, opts);
  const constitution = await readConstitutionWith(cwd, opts);

  const principlesRaw = constitution
    ? getTop5ConstitutionLines(constitution)
    : '';
  const principles = principlesRaw.length > 0
    ? principlesRaw
    : 'No constitution found — run danteforge constitution';

  const activeTasks = formatActiveTasks(state, 3);

  return `---
description: DanteForge project-specific rules for ${state.project}
globs: ['**/*']
alwaysApply: true
---

# DanteForge Project Context — ${state.project}

## Current Phase: ${state.currentPhase} (${state.workflowStage})
## Workflow Stage: ${state.workflowStage}

## Constitution Principles
${principles}

## Active Tasks
${activeTasks}

## Quality Standards
- Run \`danteforge verify\` before committing
- Run \`danteforge autoforge\` to fix quality issues
- Target PDSE score: 75+
- Follow the DanteForge workflow: constitution → spec → plan → tasks → forge → verify

## DanteForge Commands
- \`danteforge verify\` — validate current state
- \`danteforge autoforge --auto\` — autonomous quality improvement
- \`danteforge proof --prompt "..."\` — measure context quality improvement
- \`danteforge sync-context\` — regenerate this file
`;
}

export async function buildClaudeContext(
  cwd: string,
  opts: ContextSyncOptions,
): Promise<string> {
  const state = await loadStateWith(cwd, opts);
  const constitution = await readConstitutionWith(cwd, opts);

  const principlesRaw = constitution
    ? getTop5ConstitutionLines(constitution)
    : '';
  const principles = principlesRaw.length > 0
    ? principlesRaw
    : 'No constitution found — run danteforge constitution';

  const activeTasks = formatActiveTasks(state, 5);

  return `# Project Context for Claude Code — ${state.project}

This file is auto-generated by \`danteforge sync-context\`. Do not edit manually.

## Project: ${state.project}
## Current Phase: ${state.currentPhase}
## Workflow Stage: ${state.workflowStage}

## Constitution Summary
${principles}

## Active Tasks (Phase ${state.currentPhase})
${activeTasks}

## DanteForge Workflow
This project uses DanteForge for structured AI-assisted development.
- Artifacts live in \`.danteforge/\`
- Run \`danteforge verify\` to check quality
- Run \`danteforge proof --prompt "..."\` to measure AI context improvement
`;
}

export async function buildCodexContext(
  cwd: string,
  opts: ContextSyncOptions,
): Promise<string> {
  const state = await loadStateWith(cwd, opts);
  const constitution = await readConstitutionWith(cwd, opts);

  const principlesRaw = constitution
    ? getTop5ConstitutionLines(constitution)
    : '';
  const principles = principlesRaw.length > 0
    ? principlesRaw
    : 'No constitution found — run danteforge constitution';

  const activeTasks = formatActiveTasks(state, 5);

  return `# Agent Instructions — ${state.project}

Auto-generated by \`danteforge sync-context\`. Do not edit manually.

## Project Overview
Name: ${state.project}
Phase: ${state.currentPhase}
Stage: ${state.workflowStage}

## Constitution Principles
${principles}

## Current Tasks
${activeTasks}

## Constraints
- Follow DanteForge workflow pipeline
- Do not skip phases
- Run \`danteforge verify\` after code changes
- Write tests for all new code
`;
}

// ── Main sync function ────────────────────────────────────────────────────────

export async function syncContext(options: ContextSyncOptions = {}): Promise<ContextSyncResult> {
  const cwd = options.cwd ?? process.cwd();
  const rawTarget = options.target ?? 'all';

  const targets: Array<Exclude<ContextTarget, 'all'>> =
    rawTarget === 'all'
      ? ['cursor', 'claude', 'codex']
      : [rawTarget as Exclude<ContextTarget, 'all'>];

  const writeFile = options._writeFile
    ?? (async (p: string, content: string) => {
      const { writeFile: fsWrite } = await import('fs/promises');
      await fsWrite(p, content, 'utf8');
    });

  const mkdir = options._mkdir
    ?? (async (p: string, opts?: { recursive?: boolean }) => {
      const { mkdir: fsMkdir } = await import('fs/promises');
      await fsMkdir(p, opts);
    });

  const targetPaths: Record<Exclude<ContextTarget, 'all'>, string> = {
    cursor: path.join(cwd, '.cursor', 'rules', 'danteforge-project.mdc'),
    claude: path.join(cwd, 'CLAUDE.local.md'),
    codex: path.join(cwd, 'AGENTS.local.md'),
  };

  const synced: SyncedContextFile[] = [];
  const skipped: string[] = [];

  for (const target of targets) {
    try {
      let content: string;
      if (target === 'cursor') {
        content = await buildCursorContext(cwd, options);
      } else if (target === 'claude') {
        content = await buildClaudeContext(cwd, options);
      } else {
        content = await buildCodexContext(cwd, options);
      }

      const filePath = targetPaths[target];
      const parentDir = path.dirname(filePath);

      try {
        await mkdir(parentDir, { recursive: true });
      } catch {
        // best-effort — directory may already exist
      }

      await writeFile(filePath, content);

      const tokensEstimated = estimateTokens(content);
      synced.push({ target, path: filePath, content, tokensEstimated });
    } catch {
      skipped.push(target);
    }
  }

  const totalTokens = synced.reduce((sum, f) => sum + f.tokensEstimated, 0);

  return { synced, skipped, totalTokens };
}
