// default-market-dims.ts — Curated 30 market dimensions for the 50-dim baseline matrix.
// Appended after the 20 harsh-scorer dims in universe-definer.ts bootstrapMarketDims().
// selfDefault values are honest baselines — 0–3 for missing features, higher for strengths.
// Competitor baseline scores sourced from public benchmarks and feature comparisons.

export interface MarketDimSpec {
  id: string;
  label: string;
  weight: number;
  frequency: 'high' | 'medium' | 'low';
  category: string;
  selfDefault: number;
  baselineScores: Record<string, number>;
  closingStrategy?: 'code' | 'human' | 'ceiling';
  ceiling?: number;
  ceilingReason?: string;
  manualActionHint?: string;
}

export const MARKET_DIM_SPECS: MarketDimSpec[] = [
  {
    id: 'semantic_memory',
    label: 'Semantic Memory',
    weight: 1.2,
    frequency: 'high',
    category: 'features',
    selfDefault: 2.0,
    baselineScores: { Cursor: 7.0, Copilot: 6.0, Aider: 5.0, Continue: 5.0 },
  },
  {
    id: 'agent_reasoning_loop',
    label: 'Agent Reasoning Loop',
    weight: 1.3,
    frequency: 'high',
    category: 'features',
    selfDefault: 4.0,
    baselineScores: { Cursor: 8.0, Copilot: 7.0, Aider: 6.0, Continue: 5.0 },
  },
  {
    id: 'multi_agent_coordination',
    label: 'Multi-Agent Coordination',
    weight: 1.0,
    frequency: 'medium',
    category: 'features',
    selfDefault: 5.0,
    baselineScores: { Cursor: 7.0, Copilot: 5.0, Aider: 4.0, Continue: 3.0 },
  },
  {
    id: 'onboarding_ux',
    label: 'Onboarding & First-Run UX',
    weight: 1.1,
    frequency: 'high',
    category: 'ux',
    selfDefault: 2.0,
    baselineScores: { Cursor: 9.0, Copilot: 8.0, Aider: 5.0, Continue: 6.0 },
  },
  {
    id: 'ide_integration',
    label: 'IDE Integration',
    weight: 1.3,
    frequency: 'high',
    category: 'features',
    selfDefault: 5.0,
    baselineScores: { Cursor: 9.5, Copilot: 9.0, Aider: 4.0, Continue: 9.0 },
  },
  {
    id: 'context_window_management',
    label: 'Context Window Management',
    weight: 1.1,
    frequency: 'high',
    category: 'features',
    selfDefault: 5.0,
    baselineScores: { Cursor: 8.0, Copilot: 7.0, Aider: 7.0, Continue: 6.0 },
  },
  {
    id: 'tool_use_accuracy',
    label: 'Tool Use Accuracy',
    weight: 1.1,
    frequency: 'high',
    category: 'quality',
    selfDefault: 5.0,
    baselineScores: { Cursor: 8.0, Copilot: 7.5, Aider: 7.0, Continue: 6.0 },
  },
  {
    id: 'streaming_output',
    label: 'Streaming & Progress Output',
    weight: 1.0,
    frequency: 'medium',
    category: 'ux',
    selfDefault: 6.0,
    baselineScores: { Cursor: 9.0, Copilot: 8.0, Aider: 7.0, Continue: 7.0 },
  },
  {
    id: 'visual_ux_feedback',
    label: 'Visual UX Feedback',
    weight: 1.0,
    frequency: 'medium',
    category: 'ux',
    selfDefault: 6.0,
    baselineScores: { Cursor: 9.0, Copilot: 8.0, Aider: 4.0, Continue: 7.0 },
  },
  {
    id: 'code_signing',
    label: 'Code Signing',
    weight: 0.7,
    frequency: 'low',
    category: 'reliability',
    selfDefault: 0.0,
    baselineScores: { Cursor: 10.0, Copilot: 10.0, Aider: 5.0, Continue: 5.0 },
    closingStrategy: 'human',
    ceiling: 3.0,
    ceilingReason: 'requires EV certificate purchase and CA application — human action',
    manualActionHint: 'Purchase an EV code signing certificate and configure the signing pipeline',
  },
  {
    id: 'installer_distribution',
    label: 'Installer Distribution',
    weight: 0.8,
    frequency: 'low',
    category: 'reliability',
    selfDefault: 2.0,
    baselineScores: { Cursor: 10.0, Copilot: 9.0, Aider: 5.0, Continue: 6.0 },
    closingStrategy: 'human',
    ceiling: 5.0,
    ceilingReason: 'requires signed installer build pipeline — human action',
    manualActionHint: 'Set up a signed installer build pipeline for Windows/macOS/Linux',
  },
  {
    id: 'privacy_local_first',
    label: 'Privacy & Local-First',
    weight: 1.0,
    frequency: 'medium',
    category: 'reliability',
    selfDefault: 6.0,
    baselineScores: { Cursor: 5.0, Copilot: 4.0, Aider: 9.0, Continue: 9.0 },
  },
  {
    id: 'pricing_transparency',
    label: 'Pricing & Free Tier',
    weight: 0.8,
    frequency: 'medium',
    category: 'ux',
    selfDefault: 3.0,
    baselineScores: { Cursor: 8.0, Copilot: 7.0, Aider: 9.0, Continue: 9.0 },
    closingStrategy: 'human',
    ceiling: 6.0,
    ceilingReason: 'requires real users and public pricing page — human action',
    manualActionHint: 'Publish a pricing page and set up a free tier with usage limits',
  },
  {
    id: 'git_integration',
    label: 'Git Workflow Integration',
    weight: 1.2,
    frequency: 'high',
    category: 'features',
    selfDefault: 7.0,
    baselineScores: { Cursor: 9.0, Copilot: 8.0, Aider: 9.0, Continue: 7.0 },
  },
  {
    id: 'benchmark_harness',
    label: 'Benchmark Harness',
    weight: 0.9,
    frequency: 'medium',
    category: 'quality',
    selfDefault: 4.0,
    baselineScores: { Cursor: 7.0, Copilot: 6.0, Aider: 8.0, Continue: 5.0 },
  },
  {
    id: 'refactoring_safety',
    label: 'Refactoring Safety',
    weight: 1.1,
    frequency: 'high',
    category: 'quality',
    selfDefault: 5.0,
    baselineScores: { Cursor: 8.0, Copilot: 7.0, Aider: 6.0, Continue: 6.0 },
  },
  {
    id: 'multi_file_editing',
    label: 'Multi-File Editing',
    weight: 1.2,
    frequency: 'high',
    category: 'features',
    selfDefault: 7.0,
    baselineScores: { Cursor: 9.0, Copilot: 8.0, Aider: 8.0, Continue: 7.0 },
  },
  {
    id: 'language_support_breadth',
    label: 'Language Support Breadth',
    weight: 1.0,
    frequency: 'medium',
    category: 'features',
    selfDefault: 6.0,
    baselineScores: { Cursor: 9.0, Copilot: 9.0, Aider: 8.0, Continue: 8.0 },
  },
  {
    id: 'custom_instructions',
    label: 'Custom Instructions / Constitution',
    weight: 1.0,
    frequency: 'medium',
    category: 'features',
    selfDefault: 8.0,
    baselineScores: { Cursor: 7.0, Copilot: 5.0, Aider: 6.0, Continue: 7.0 },
  },
  {
    id: 'model_provider_choice',
    label: 'Model Provider Choice',
    weight: 1.0,
    frequency: 'medium',
    category: 'features',
    selfDefault: 7.0,
    baselineScores: { Cursor: 6.0, Copilot: 3.0, Aider: 8.0, Continue: 9.0 },
  },
  {
    id: 'workflow_resumability',
    label: 'Workflow Resumability',
    weight: 1.0,
    frequency: 'medium',
    category: 'features',
    selfDefault: 6.0,
    baselineScores: { Cursor: 7.0, Copilot: 5.0, Aider: 7.0, Continue: 5.0 },
  },
  {
    id: 'audit_trail_depth',
    label: 'Audit Trail Depth',
    weight: 0.9,
    frequency: 'medium',
    category: 'reliability',
    selfDefault: 7.0,
    baselineScores: { Cursor: 5.0, Copilot: 4.0, Aider: 6.0, Continue: 4.0 },
  },
  {
    id: 'test_generation',
    label: 'Automated Test Generation',
    weight: 1.1,
    frequency: 'high',
    category: 'quality',
    selfDefault: 5.0,
    baselineScores: { Cursor: 8.0, Copilot: 8.0, Aider: 6.0, Continue: 6.0 },
  },
  {
    id: 'documentation_sync',
    label: 'Documentation Sync',
    weight: 0.9,
    frequency: 'medium',
    category: 'ux',
    selfDefault: 4.0,
    baselineScores: { Cursor: 6.0, Copilot: 7.0, Aider: 5.0, Continue: 5.0 },
  },
  {
    id: 'terminal_integration',
    label: 'Terminal Integration',
    weight: 1.0,
    frequency: 'medium',
    category: 'features',
    selfDefault: 6.0,
    baselineScores: { Cursor: 8.0, Copilot: 6.0, Aider: 9.0, Continue: 7.0 },
  },
  {
    id: 'deployment_integration',
    label: 'Deployment Integration',
    weight: 0.8,
    frequency: 'low',
    category: 'features',
    selfDefault: 2.0,
    baselineScores: { Cursor: 6.0, Copilot: 6.0, Aider: 4.0, Continue: 4.0 },
  },
  {
    id: 'web_search_integration',
    label: 'Web Search Integration',
    weight: 0.8,
    frequency: 'medium',
    category: 'features',
    selfDefault: 2.0,
    baselineScores: { Cursor: 7.0, Copilot: 7.0, Aider: 4.0, Continue: 5.0 },
  },
  {
    id: 'competitive_intelligence',
    label: 'Competitive Intelligence',
    weight: 1.0,
    frequency: 'medium',
    category: 'features',
    selfDefault: 7.0,
    baselineScores: { Cursor: 3.0, Copilot: 2.0, Aider: 2.0, Continue: 2.0 },
  },
  {
    id: 'swe_bench_performance',
    label: 'SWE-bench Performance',
    weight: 1.1,
    frequency: 'high',
    category: 'quality',
    selfDefault: 3.0,
    baselineScores: { Cursor: 8.0, Copilot: 7.0, Aider: 7.5, Continue: 5.0 },
  },
  {
    id: 'voice_interface',
    label: 'Voice Interface',
    weight: 0.5,
    frequency: 'low',
    category: 'ux',
    selfDefault: 0.0,
    baselineScores: { Cursor: 2.0, Copilot: 2.0, Aider: 0.0, Continue: 0.0 },
    ceiling: 4.0,
    ceilingReason: 'limited market demand for CLI voice; ceiling reflects realistic adoption',
  },
];
