// git-integration.ts — Stage/commit, branch, and PR helpers with injection seams
import path from 'path';
import type { DanteState } from './state.js';
import { logGitOperation, generateCorrelationId } from './structured-audit.js';

export interface CommitMessageOptions {
  state: DanteState;
  changedFiles?: string[];
  prefix?: string; // override auto-detected type
}

export interface PRBodyOptions {
  spec?: string;   // content of SPEC.md
  plan?: string;   // content of PLAN.md
  tasks?: string;  // content of TASKS.md
  project: string;
  phase: number;
}

export interface SimpleGitLike {
  add(files: string[]): Promise<unknown>;
  commit(message: string): Promise<{ commit: string }>;
  checkoutLocalBranch(name: string): Promise<void>;
  status(): Promise<{ files: Array<{ path: string }> }>;
}

export interface GitIntegrationOptions {
  cwd?: string;
  _git?: SimpleGitLike;
  _readFile?: (p: string) => Promise<string>;
  _exists?: (p: string) => Promise<boolean>;
  filesToStage?: string[];
}

// ─── helpers ──────────────────────────────────────────────────────────────────

function slugify(text: string, maxLen: number): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLen)
    .replace(/-+$/, '');
}

// ─── Pure functions ────────────────────────────────────────────────────────────

/**
 * Generate a conventional-commit message from current DanteForge state.
 * Pure function — no I/O.
 */
export function generateCommitMessage(opts: CommitMessageOptions): string {
  const { state } = opts;

  let type: string;
  if (opts.prefix) {
    type = opts.prefix;
  } else {
    switch (state.workflowStage) {
      case 'forge':
        type = 'feat';
        break;
      case 'verify':
        type = 'test';
        break;
      case 'plan':
      case 'tasks':
      case 'specify':
      case 'clarify':
        type = 'docs';
        break;
      default:
        type = 'chore';
    }
  }

  const scope = slugify(state.project, 20);
  const taskName = state.tasks?.[state.currentPhase]?.[0]?.name ?? state.workflowStage;
  const taskSlug = slugify(taskName, 50);

  return `${type}(${scope}): ${taskSlug}`;
}

/**
 * Generate a git branch name from current DanteForge state.
 * Pure function — no I/O.
 */
export function generateBranchName(state: DanteState): string {
  const projectSlug = slugify(state.project, 30);
  const phase = state.currentPhase;
  const taskName = state.tasks?.[state.currentPhase]?.[0]?.name ?? 'task';
  const taskSlug = slugify(taskName, 40);

  // Build each segment separately so double-dashes don't cross boundaries
  const segments = [projectSlug, `${phase}-${taskSlug}`].map(s =>
    s.replace(/-{2,}/g, '-').replace(/^-+|-+$/g, ''),
  );

  return `danteforge/${segments[0]}/${segments[1]}`;
}

/**
 * Generate a PR body markdown string.
 * Pure async function — no I/O.
 */
export async function generatePRBody(opts: PRBodyOptions): Promise<string> {
  const specContent = opts.spec ? opts.spec.slice(0, 500) : 'No spec available';
  const planContent = opts.plan ? opts.plan.slice(0, 500) : 'No plan available';
  const tasksContent = opts.tasks ? opts.tasks.slice(0, 500) : 'No tasks available';

  return [
    `## Summary\n${specContent}`,
    `## Changes\n${planContent}`,
    `## Tasks\n${tasksContent}`,
    `## Quality\nPhase: ${opts.phase}\nProject: ${opts.project}`,
    `\n---\n🤖 Generated by DanteForge`,
  ].join('\n\n');
}

// ─── Async operations ──────────────────────────────────────────────────────────

async function resolveGit(opts: GitIntegrationOptions | undefined): Promise<SimpleGitLike> {
  if (opts?._git) return opts._git;
  const { simpleGit } = await import('simple-git');
  return simpleGit({ baseDir: opts?.cwd ?? process.cwd() }) as unknown as SimpleGitLike;
}

/**
 * Stage all changed files and commit with a task-derived message.
 */
export async function stageAndCommit(
  state: DanteState,
  opts?: GitIntegrationOptions,
): Promise<{ committed: boolean; message: string; filesStaged: number }> {
  const correlationId = generateCorrelationId();
  try {
    const git = await resolveGit(opts);
    let changedFiles: string[];
    if (opts?.filesToStage && opts.filesToStage.length > 0) {
      changedFiles = opts.filesToStage;
    } else {
      const statusResult = await git.status();
      changedFiles = statusResult.files.map(f => f.path);
    }
    await git.add(changedFiles);
    const message = generateCommitMessage({ state, changedFiles });
    await git.commit(message);
    logGitOperation('commit', correlationId, 'success', opts?.cwd);
    return { committed: true, message, filesStaged: changedFiles.length };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    logGitOperation('commit', correlationId, 'failure', opts?.cwd);
    return { committed: false, message, filesStaged: 0 };
  }
}

/**
 * Create a new git branch named after the current task.
 */
export async function createTaskBranch(
  state: DanteState,
  opts?: GitIntegrationOptions,
): Promise<{ created: boolean; branchName: string }> {
  const branchName = generateBranchName(state);
  try {
    const git = await resolveGit(opts);
    await git.checkoutLocalBranch(branchName);
    return { created: true, branchName };
  } catch {
    return { created: false, branchName };
  }
}

/**
 * Open a PR via the `gh` CLI, generating the body from DanteForge artifacts.
 * Falls back gracefully when `gh` is not available.
 */
export async function openPullRequest(
  state: DanteState,
  opts?: GitIntegrationOptions & { baseBranch?: string; draft?: boolean },
): Promise<{ url: string; prNumber: number }> {
  const cwd = opts?.cwd ?? process.cwd();

  // Read artifacts best-effort
  const readFile = opts?._readFile ?? (async (p: string) => {
    const { readFile: fsReadFile } = await import('node:fs/promises');
    return fsReadFile(p, 'utf-8');
  });

  const tryRead = async (relativePath: string): Promise<string | undefined> => {
    try {
      return await readFile(path.join(cwd, relativePath));
    } catch {
      return undefined;
    }
  };

  const [spec, plan, tasks] = await Promise.all([
    tryRead('.danteforge/SPEC.md'),
    tryRead('.danteforge/PLAN.md'),
    tryRead('.danteforge/TASKS.md'),
  ]);

  const body = await generatePRBody({
    spec,
    plan,
    tasks,
    project: state.project,
    phase: state.currentPhase,
  });

  const branchName = generateBranchName(state);
  const title = generateCommitMessage({ state });

  try {
    const { execFile } = await import('node:child_process');
    const { promisify } = await import('node:util');
    const execFileAsync = promisify(execFile);

    const args = ['pr', 'create', '--title', title, '--body', body];
    if (opts?.baseBranch) args.push('--base', opts.baseBranch);
    if (opts?.draft) args.push('--draft');
    args.push('--head', branchName);

    const { stdout } = await execFileAsync('gh', args, { cwd });
    const url = stdout.trim().split('\n').find(l => l.startsWith('http')) ?? stdout.trim();
    const match = url.match(/\/pull\/(\d+)/);
    const prNumber = match ? parseInt(match[1], 10) : 0;
    return { url, prNumber };
  } catch {
    return { url: 'not-created', prNumber: 0 };
  }
}
