// First-run onboarding wizard — guides new users through DanteForge setup
// Detects missing STATE.yaml / config.yaml and walks through project setup.

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

// ---------------------------------------------------------------------------
// Types & injection seams
// ---------------------------------------------------------------------------

export type ProjectType = 'web-app' | 'cli' | 'library' | 'monorepo' | 'other';
export type ProviderChoice = 'ollama' | 'claude' | 'openai' | 'grok' | 'gemini';

export interface OnboardingOptions {
  /** Inject a custom readline fn for testing. Receives a prompt and returns the answer. */
  _readlineFn?: (prompt: string) => Promise<string>;
  /** Inject a custom writer for testing (defaults to process.stdout.write). */
  _writeFn?: (msg: string) => void;
  /** Override global config directory (defaults to ~/.danteforge). */
  _configDir?: string;
}

interface OnboardingState {
  projectType: ProjectType;
  provider: ProviderChoice;
  projectName: string;
}

// ---------------------------------------------------------------------------
// First-run detection
// ---------------------------------------------------------------------------

/** Returns true if the project has not been initialized yet. */
export function isFirstRun(cwd: string, configDir?: string): boolean {
  const stateFile = path.join(cwd, '.danteforge', 'STATE.yaml');
  const globalConfig = path.join(configDir ?? path.join(os.homedir(), '.danteforge'), 'config.yaml');
  return !fs.existsSync(stateFile) && !fs.existsSync(globalConfig);
}

/** Returns true if CONSTITUTION.md is missing in the project. */
export function isConstitutionMissing(cwd: string): boolean {
  return !fs.existsSync(path.join(cwd, 'CONSTITUTION.md'));
}

// ---------------------------------------------------------------------------
// Template generators
// ---------------------------------------------------------------------------

const CONSTITUTION_TEMPLATE = (projectName: string, projectType: ProjectType): string => `# Constitution — ${projectName}

## Purpose
> Describe the core purpose and mission of this project.

## Project Type
${projectType}

## Quality Standards
- Every feature must have tests before code (TDD)
- No stubs or TODO-only implementations shipped to production
- All LLM-generated code is reviewed before merge
- Error messages must be actionable and suggest next steps

## Architecture Principles
- Keep files under 500 lines (hard cap: 750)
- Prefer pure functions with injected dependencies for testability
- Document non-obvious decisions in code comments

## Definition of Done
- [ ] Tests pass (npm run verify)
- [ ] No TypeScript errors (npm run typecheck)
- [ ] Feature works end-to-end in the target environment
- [ ] CHANGELOG entry added
`;

const CONFIG_TEMPLATE = (provider: ProviderChoice): string => `# DanteForge global config
# Generated by onboarding wizard

llmProvider: ${provider}
${provider === 'ollama' ? 'ollamaModel: llama3\nollamaBaseUrl: http://localhost:11434' : '# Add your API key: apiKey: YOUR_KEY_HERE'}
`;

// ---------------------------------------------------------------------------
// Next-steps checklist
// ---------------------------------------------------------------------------

const NEXT_STEPS = [
  '1. Run `danteforge constitution` to refine your CONSTITUTION.md',
  '2. Run `danteforge specify` to write your project spec',
  '3. Run `danteforge plan` to generate an implementation plan',
  '4. Run `danteforge tasks` to break the plan into tasks',
  '5. Run `danteforge forge` to execute the first wave',
  '',
  'Tip: Run `danteforge flow` anytime to see the workflow decision tree.',
  'Tip: Run `danteforge go` for the daily driver experience.',
];

// ---------------------------------------------------------------------------
// Core wizard logic
// ---------------------------------------------------------------------------

function defaultWrite(msg: string): void {
  process.stdout.write(msg + '\n');
}

async function askQuestion(
  prompt: string,
  readlineFn: (p: string) => Promise<string>,
): Promise<string> {
  return (await readlineFn(prompt)).trim();
}

async function selectProjectType(
  readlineFn: (p: string) => Promise<string>,
  write: (msg: string) => void,
): Promise<ProjectType> {
  write('\nWhat type of project is this?');
  write('  1) Web app');
  write('  2) CLI tool');
  write('  3) Library / package');
  write('  4) Monorepo');
  write('  5) Other');
  const answer = await askQuestion('Enter number [1-5]: ', readlineFn);
  const map: Record<string, ProjectType> = {
    '1': 'web-app',
    '2': 'cli',
    '3': 'library',
    '4': 'monorepo',
    '5': 'other',
  };
  return map[answer] ?? 'other';
}

async function selectProvider(
  readlineFn: (p: string) => Promise<string>,
  write: (msg: string) => void,
): Promise<ProviderChoice> {
  write('\nWhich LLM provider do you want to use?');
  write('  1) Ollama  (local, free — recommended for first time)');
  write('  2) Claude  (Anthropic API key required)');
  write('  3) OpenAI  (API key required)');
  write('  4) Grok    (xAI API key required)');
  write('  5) Gemini  (Google API key required)');
  const answer = await askQuestion('Enter number [1-5]: ', readlineFn);
  const map: Record<string, ProviderChoice> = {
    '1': 'ollama',
    '2': 'claude',
    '3': 'openai',
    '4': 'grok',
    '5': 'gemini',
  };
  return map[answer] ?? 'ollama';
}

// ---------------------------------------------------------------------------
// File creation helpers (best-effort, no throws)
// ---------------------------------------------------------------------------

function ensureDir(dir: string): void {
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    // best-effort
  }
}

function writeFileIfMissing(filePath: string, content: string): boolean {
  if (fs.existsSync(filePath)) return false;
  try {
    ensureDir(path.dirname(filePath));
    fs.writeFileSync(filePath, content, 'utf8');
    return true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Run the first-time onboarding wizard.
 * Safe to call multiple times — exits immediately if already initialized.
 */
export async function runOnboardingWizard(
  cwd: string,
  options: OnboardingOptions = {},
): Promise<void> {
  const write = options._writeFn ?? defaultWrite;
  const configDir = options._configDir ?? path.join(os.homedir(), '.danteforge');

  if (!isFirstRun(cwd, configDir)) {
    return; // already initialized — nothing to do
  }

  write('');
  write('╔══════════════════════════════════════════════════════╗');
  write('║   Welcome to DanteForge — First-Run Setup Wizard    ║');
  write('╚══════════════════════════════════════════════════════╝');
  write('');
  write('DanteForge needs a few details to set up your project.');

  // Require a readline fn — callers must provide real readline or a test double
  const readlineFn = options._readlineFn;
  if (!readlineFn) {
    // Non-interactive fallback: write instructions and exit
    write('');
    write('Run `danteforge init` to complete setup interactively.');
    write('');
    return;
  }

  const projectName = await askQuestion('\nProject name (or press Enter to use folder name): ', readlineFn);
  const resolvedName = projectName || path.basename(cwd);

  const state: OnboardingState = {
    projectName: resolvedName,
    projectType: await selectProjectType(readlineFn, write),
    provider: await selectProvider(readlineFn, write),
  };

  write('\nSetting up your project...');

  // Write global config
  const configPath = path.join(configDir, 'config.yaml');
  const wroteConfig = writeFileIfMissing(configPath, CONFIG_TEMPLATE(state.provider));
  if (wroteConfig) {
    write(`  Created global config at ${configPath}`);
  }

  // Write CONSTITUTION.md
  const constitutionPath = path.join(cwd, 'CONSTITUTION.md');
  const wroteConstitution = writeFileIfMissing(
    constitutionPath,
    CONSTITUTION_TEMPLATE(state.projectName, state.projectType),
  );
  if (wroteConstitution) {
    write(`  Created ${constitutionPath}`);
  }

  // Initialize .danteforge directory
  const danteforgeDir = path.join(cwd, '.danteforge');
  ensureDir(danteforgeDir);

  write('');
  write('Setup complete! Next steps:');
  write('');
  for (const step of NEXT_STEPS) {
    write(step);
  }
  write('');
}
