export const DANTEFORGE_VERSION = '0.17.0';

export function generatedByLine(): string {
  return `*Generated by [DanteForge](https://github.com/dantericardo88/danteforge) v${DANTEFORGE_VERSION}*`;
}
