// Critique — adversarial plan review command.
// Finds gaps before they become bugs: platform issues, missing injection seams,
// schema problems, security assumptions, interaction conflicts, and more.
//
// Usage:
//   danteforge critique <plan-file>
//   danteforge critique <plan-file> --source src/core/oss-intel.ts
//   danteforge critique <plan-file> --stakes critical
//   danteforge critique <plan-file> --diff HEAD~1
//   danteforge critique <plan-file> --auto-refine
//   danteforge critique <plan-file> --json

import fs from 'fs/promises';
import path from 'path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { logger } from '../../core/logger.js';
import { withErrorBoundary } from '../../core/cli-error-boundary.js';
import {
  critiquePlan,
  printCritiqueReport,
  type CritiqueReport,
  type CritiqueStakes,
  type CritiquePersona,
  type PlanCriticOptions,
} from '../../core/plan-critic.js';
import { recordCritiqueLesson } from '../../core/lessons-index.js';

const execFileAsync = promisify(execFile);

// ── Types ─────────────────────────────────────────────────────────────────────

export interface CritiqueCommandOptions {
  source?: string;          // comma-separated source files
  autoRefine?: boolean;     // feed blocking gaps back into plan as annotations
  json?: boolean;
  skipCritique?: boolean;   // escape hatch
  stakes?: string;          // 'low'|'medium'|'high'|'critical'
  diff?: string;            // git ref for diff mode (e.g. 'HEAD~1')
  premortem?: boolean;      // default true
  cwd?: string;
  _llmCaller?: (prompt: string) => Promise<string>;
  _isLLMAvailable?: () => Promise<boolean>;
  _readFile?: (filePath: string) => Promise<string>;
  _gitDiff?: (ref: string, cwd: string) => Promise<string>;
}

// ── Git diff helper ───────────────────────────────────────────────────────────

async function defaultGitDiff(ref: string, cwd: string): Promise<string> {
  const result = await execFileAsync('git', ['diff', ref], { cwd, timeout: 15_000 });
  return result.stdout;
}

// ── Auto-refine: annotate plan with gaps ──────────────────────────────────────

async function autoRefinePlan(
  planFile: string,
  report: CritiqueReport,
  readFile: (p: string) => Promise<string>,
): Promise<void> {
  try {
    const content = await readFile(planFile);
    const blockingGaps = report.gapsFound.filter(g => g.severity === 'blocking');
    if (blockingGaps.length === 0) return;

    const annotation = [
      '',
      '---',
      '## Critique Annotations (auto-generated)',
      `> Generated by \`danteforge critique\` — ${new Date().toISOString()}`,
      '',
      ...blockingGaps.map((g, i) =>
        `### Gap ${i + 1}: [${g.category}] ${g.description}\n**Fix:** ${g.specificFix}`,
      ),
    ].join('\n');

    await fs.writeFile(planFile, content + annotation, 'utf8');
    logger.info(`[critique] Plan annotated with ${blockingGaps.length} blocking gaps → ${planFile}`);
  } catch (err) {
    logger.warn(`[critique] Auto-refine failed: ${err instanceof Error ? err.message : String(err)}`);
  }
}

// ── Context loader ────────────────────────────────────────────────────────────

async function loadCritiqueContext(
  opts: CritiqueCommandOptions,
  cwd: string,
): Promise<{ sourceFilePaths: string[]; diffContent: string | undefined }> {
  const sourceFilePaths = opts.source
    ? opts.source.split(',').map(s => s.trim()).filter(Boolean)
    : [];
  let diffContent: string | undefined;
  if (opts.diff) {
    try {
      const gitDiffFn = opts._gitDiff ?? defaultGitDiff;
      diffContent = await gitDiffFn(opts.diff, cwd);
      logger.info(`[critique] Loaded diff from ${opts.diff} (${diffContent.length} chars)`);
    } catch (err) {
      logger.warn(`[critique] Failed to load diff: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  return { sourceFilePaths, diffContent };
}

// ── Main command ──────────────────────────────────────────────────────────────

export async function critique(
  planFile: string,
  opts: CritiqueCommandOptions = {},
): Promise<void> {
  return withErrorBoundary('critique', async () => {
    const cwd = opts.cwd ?? process.cwd();

    // Escape hatch
    if (opts.skipCritique) {
      logger.info('[critique] Skipped (--skip-critique)');
      return;
    }

    // Validate plan file exists
    const planPath = path.isAbsolute(planFile) ? planFile : path.join(cwd, planFile);
    const readFile = opts._readFile ?? ((p: string) => fs.readFile(p, 'utf8'));

    let planContent: string;
    try {
      planContent = await readFile(planPath);
    } catch {
      logger.error(`[critique] Plan file not found: ${planPath}`);
      process.exitCode = 1;
      return;
    }

    const { sourceFilePaths, diffContent } = await loadCritiqueContext(opts, cwd);

    // Validate stakes
    const validStakes: CritiqueStakes[] = ['low', 'medium', 'high', 'critical'];
    const stakes: CritiqueStakes = validStakes.includes(opts.stakes as CritiqueStakes)
      ? (opts.stakes as CritiqueStakes)
      : 'medium';

    // In JSON mode suppress informational logs so stdout is clean JSON
    if (opts.json) logger.setLevel('error');

    logger.info(`[critique] Analysing ${path.basename(planPath)} [stakes: ${stakes}]...`);

    const criticOpts: PlanCriticOptions = {
      cwd,
      planContent,
      sourceFilesToRead: sourceFilePaths,
      stakes,
      enablePremortem: opts.premortem !== false,
      diffContent,
      _llmCaller: opts._llmCaller,
      _isLLMAvailable: opts._isLLMAvailable,
      _readFile: opts._readFile,
    };

    const report = await critiquePlan(criticOpts);

    // Output
    if (opts.json) {
      process.stdout.write(JSON.stringify(report, null, 2) + '\n');
    } else {
      printCritiqueReport(report);
    }

    // Auto-refine: annotate plan with blocking gaps
    if (opts.autoRefine && !report.approved) {
      await autoRefinePlan(planPath, report, readFile);
    }

    // Record blocking gaps as lessons (best-effort)
    if (!report.approved) {
      for (const gap of report.gapsFound.filter(g => g.severity === 'blocking')) {
        await recordCritiqueLesson(gap, path.basename(planPath), cwd).catch(() => {});
      }
    }

    // Set exit code
    if (!report.approved) {
      logger.warn(
        `[critique] ${report.blockingCount} blocking gap(s) found. ` +
        `Resolve before running 'danteforge tasks'.`,
      );
      process.exitCode = 1;
    } else {
      logger.info('[critique] Plan approved — 0 blocking gaps.');
    }
  });
}

// ── Re-export for plan.ts integration ────────────────────────────────────────

export { critiquePlan, printCritiqueReport } from '../../core/plan-critic.js';
