// guide — Project-specific contextual guide generator
// Reads current project state and generates .danteforge/GUIDE.md for use with @GUIDE.md

import fs from 'fs/promises';
import path from 'path';
import { logger } from '../../core/logger.js';

export interface GuideOptions {
  cwd?: string;
  _loadState?: () => Promise<string | null>;
  _readGoal?: () => Promise<string | null>;
  _readScore?: () => Promise<number | null>;
  _writeGuide?: (content: string) => Promise<void>;
}

export interface GuideResult {
  written: boolean;
  guidePath: string;
  stage?: string;
  score?: number | null;
}

function stageNextAction(stage: string | undefined, phase: string | undefined): string {
  switch (stage) {
    case 'forge':
      return `Run \`/forge\` to continue implementing phase ${phase ?? '?'}`;
    case 'specify':
      return 'Run `/clarify` to sharpen the spec';
    case 'clarify':
      return 'Run `/tech-decide`, then `/plan`';
    case 'plan':
      return 'Run `/tasks` to break the plan into execution tasks';
    case 'tasks':
      return 'Run `/forge` to begin implementation';
    case 'verify':
      return 'Run `/synthesize` to finalize, then `/ship` when ready';
    case 'synthesize':
      return 'Run `/ship` to cut a release';
    default:
      return 'Run `/danteforge-flow` to choose your workflow';
  }
}

function commandsForStage(stage: string | undefined): string[] {
  switch (stage) {
    case 'forge':   return ['/forge — implement the next wave', '/verify — check that everything passes', '/outcome-check — validate patterns helped'];
    case 'verify':  return ['/self-assess — objective quality score', '/self-mutate — test coverage validation', '/ci-report — CI regression gate'];
    case 'specify': return ['/clarify — sharpen the spec', '/plan — generate implementation plan'];
    case 'plan':    return ['/tasks — break plan into tasks', '/forge — begin implementation'];
    default:        return ['/danteforge-flow — choose your workflow', '/self-assess — check current quality'];
  }
}

function buildGuideContent(
  project: string | undefined,
  stage: string | undefined,
  phase: string | undefined,
  score: number | null,
  goal: string | null
): string {
  const projectName = project ?? 'this project';
  const scoreStr = score !== null && score !== undefined ? `${score.toFixed(1)}/10` : 'not yet measured';
  const goalStr = goal ? `\n- Goal: ${goal.trim()}` : '';
  const nextAction = stageNextAction(stage, phase);
  const commands = commandsForStage(stage);

  return [
    `# DanteForge Guide — ${projectName}`,
    ``,
    `## Current State`,
    `- Stage: ${stage ?? 'not initialized'}${phase ? ` (phase ${phase})` : ''}`,
    `- Quality score: ${scoreStr}${goalStr}`,
    ``,
    `## What to do right now`,
    nextAction,
    ``,
    `## Commands you'll use most`,
    ...commands.map(c => `- \`${c}\``),
    ``,
    `## When things go wrong`,
    `- Score not improving? Run \`/status\` then \`/respec\``,
    `- Tests failing? Run \`/self-mutate\` to find weak coverage`,
    `- Imported bad patterns? Run \`/refused-patterns\` to block them`,
    `- Need a fresh start? Run \`/danteforge-flow\` to pick a new workflow`,
    ``,
    `---`,
    `_Generated by \`danteforge guide\`. Reload with \`@.danteforge/GUIDE.md\` in any session._`,
  ].join('\n');
}

export async function runGuide(options: GuideOptions = {}): Promise<GuideResult> {
  const cwd = options.cwd ?? process.cwd();
  const guidePath = path.join(cwd, '.danteforge', 'GUIDE.md');

  const loadState = options._loadState ?? (async () => {
    try {
      return await fs.readFile(path.join(cwd, '.danteforge', 'STATE.yaml'), 'utf8');
    } catch {
      return null;
    }
  });

  const readGoal = options._readGoal ?? (async () => {
    try {
      return await fs.readFile(path.join(cwd, '.danteforge', 'goal.md'), 'utf8');
    } catch {
      return null;
    }
  });

  const readScore = options._readScore ?? (async () => {
    try {
      const snapDir = path.join(cwd, '.danteforge', 'snapshots');
      const entries = await fs.readdir(snapDir);
      const latest = entries.sort().at(-1);
      if (!latest) return null;
      const raw = await fs.readFile(path.join(snapDir, latest), 'utf8');
      const parsed = JSON.parse(raw) as { hybridScore?: number };
      return typeof parsed.hybridScore === 'number' ? parsed.hybridScore : null;
    } catch {
      return null;
    }
  });

  const writeGuide = options._writeGuide ?? (async (content: string) => {
    await fs.mkdir(path.join(cwd, '.danteforge'), { recursive: true });
    await fs.writeFile(guidePath, content, 'utf8');
  });

  const stateYaml = await loadState();
  let stage: string | undefined;
  let phase: string | undefined;
  let project: string | undefined;

  if (stateYaml) {
    stage   = stateYaml.match(/^workflowStage:\s*(.+)$/m)?.[1]?.trim();
    phase   = stateYaml.match(/^currentPhase:\s*(.+)$/m)?.[1]?.trim();
    project = stateYaml.match(/^project:\s*(.+)$/m)?.[1]?.trim();
  }

  const [score, goal] = await Promise.all([readScore(), readGoal()]);
  const content = buildGuideContent(project, stage, phase, score, goal);

  await writeGuide(content);

  logger.info(`Guide written to ${guidePath}`);
  logger.info(`Load it in any Claude Code session: @.danteforge/GUIDE.md`);

  return { written: true, guidePath, stage, score };
}
