// Headless Renderer — Native SVG-based design preview generation
// No external WASM or canvas dependencies. Generates SVG from .op documents
// for terminal preview and HTML output.

import type { OPDocument, OPNode, OPFill, OPStroke, OPEffect } from './op-codec.js';

/**
 * Render an OPDocument to an SVG string.
 * This is a native, zero-dependency renderer.
 */
export function renderToSVG(doc: OPDocument): string {
  const rootNode = doc.nodes[0];
  if (!rootNode) {
    return '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><text x="10" y="50">Empty design</text></svg>';
  }

  const width = rootNode.width ?? 1440;
  const height = rootNode.height ?? 900;

  const lines: string[] = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`,
    '  <style>',
    '    text { font-family: Inter, system-ui, -apple-system, sans-serif; }',
    '  </style>',
  ];

  // Add defs for shadows/filters
  const filters = collectFilters(doc.nodes);
  if (filters.length > 0) {
    lines.push('  <defs>');
    for (const filter of filters) {
      lines.push(`    ${filter}`);
    }
    lines.push('  </defs>');
  }

  // Render all top-level nodes
  for (const node of doc.nodes) {
    renderNode(node, lines, 2);
  }

  lines.push('</svg>');
  return lines.join('\n');
}

/**
 * Render an OPDocument to an ASCII layout schematic for terminal output.
 * Fallback when SVG is not suitable (e.g., pure CLI environments).
 */
export function renderToASCII(doc: OPDocument): string {
  const rootNode = doc.nodes[0];
  if (!rootNode) return '┌─ Empty Design ─┐\n│                │\n└────────────────┘';

  const lines: string[] = [];
  renderNodeASCII(rootNode, lines, 0);
  return lines.join('\n');
}

/**
 * Generate an HTML preview file that can be opened in a browser.
 */
export function renderToHTML(doc: OPDocument): string {
  const svg = renderToSVG(doc);
  const title = doc.document.name ?? 'Design Preview';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHTML(title)} — DanteForge Design Preview</title>
  <style>
    body { margin: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #f1f5f9; font-family: system-ui; }
    .preview { background: white; box-shadow: 0 4px 24px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden; }
    .meta { padding: 12px 16px; background: #1e293b; color: #e2e8f0; font-size: 13px; display: flex; justify-content: space-between; }
  </style>
</head>
<body>
  <div class="preview">
    <div class="meta">
      <span>${escapeHTML(title)}</span>
      <span>Generated by DanteForge v0.10.0</span>
    </div>
    ${svg}
  </div>
</body>
</html>`;
}

// ── Internal SVG rendering ──

function renderNode(node: OPNode, lines: string[], indent: number): void {
  const pad = '  '.repeat(indent);

  switch (node.type) {
    case 'frame':
    case 'group':
    case 'component':
    case 'instance':
      renderFrame(node, lines, indent);
      break;
    case 'rectangle':
      renderRect(node, lines, indent);
      break;
    case 'ellipse':
      renderEllipse(node, lines, indent);
      break;
    case 'text':
      renderText(node, lines, indent);
      break;
    case 'line':
      renderLine(node, lines, indent);
      break;
    default:
      // Generic rect fallback for unknown types
      renderRect(node, lines, indent);
  }
}

function renderFrame(node: OPNode, lines: string[], indent: number): void {
  const pad = '  '.repeat(indent);
  const x = node.x ?? 0;
  const y = node.y ?? 0;
  const w = node.width ?? 100;
  const h = node.height ?? 100;
  const fill = getFillColor(node.fills);
  const stroke = getStrokeAttrs(node.strokes);
  const opacity = node.opacity !== undefined ? ` opacity="${node.opacity}"` : '';
  const rx = node.cornerRadius ? ` rx="${node.cornerRadius}"` : '';
  const filter = getFilterAttr(node);

  lines.push(`${pad}<g data-name="${escapeAttr(node.name ?? '')}">`);
  lines.push(`${pad}  <rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}"${rx}${stroke}${opacity}${filter}/>`);

  if (node.children) {
    for (const child of node.children) {
      renderNode(child, lines, indent + 1);
    }
  }

  lines.push(`${pad}</g>`);
}

function renderRect(node: OPNode, lines: string[], indent: number): void {
  const pad = '  '.repeat(indent);
  const x = node.x ?? 0;
  const y = node.y ?? 0;
  const w = node.width ?? 50;
  const h = node.height ?? 50;
  const fill = getFillColor(node.fills);
  const stroke = getStrokeAttrs(node.strokes);
  const rx = node.cornerRadius ? ` rx="${node.cornerRadius}"` : '';
  const opacity = node.opacity !== undefined ? ` opacity="${node.opacity}"` : '';

  lines.push(`${pad}<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}"${rx}${stroke}${opacity} data-name="${escapeAttr(node.name ?? '')}"/>`);
}

function renderEllipse(node: OPNode, lines: string[], indent: number): void {
  const pad = '  '.repeat(indent);
  const w = node.width ?? 50;
  const h = node.height ?? 50;
  const cx = (node.x ?? 0) + w / 2;
  const cy = (node.y ?? 0) + h / 2;
  const fill = getFillColor(node.fills);
  const stroke = getStrokeAttrs(node.strokes);

  lines.push(`${pad}<ellipse cx="${cx}" cy="${cy}" rx="${w / 2}" ry="${h / 2}" fill="${fill}"${stroke} data-name="${escapeAttr(node.name ?? '')}"/>`);
}

function renderText(node: OPNode, lines: string[], indent: number): void {
  const pad = '  '.repeat(indent);
  const x = node.x ?? 0;
  const y = node.y ?? 0;
  const size = node.fontSize ?? 16;
  const family = node.fontFamily ?? 'Inter';
  const weight = node.fontWeight ?? 400;
  const fill = getFillColor(node.fills) || '#000000';
  const anchor = node.textAlign === 'center' ? 'middle' : node.textAlign === 'right' ? 'end' : 'start';
  const text = escapeHTML(node.characters ?? '');

  lines.push(`${pad}<text x="${x}" y="${y + size}" font-size="${size}" font-family="${escapeAttr(family)}" font-weight="${weight}" fill="${fill}" text-anchor="${anchor}" data-name="${escapeAttr(node.name ?? '')}">${text}</text>`);
}

function renderLine(node: OPNode, lines: string[], indent: number): void {
  const pad = '  '.repeat(indent);
  const x = node.x ?? 0;
  const y = node.y ?? 0;
  const w = node.width ?? 100;
  const stroke = node.strokes?.[0]?.color ?? '#000000';
  const weight = node.strokes?.[0]?.weight ?? 1;

  lines.push(`${pad}<line x1="${x}" y1="${y}" x2="${x + w}" y2="${y}" stroke="${stroke}" stroke-width="${weight}" data-name="${escapeAttr(node.name ?? '')}"/>`);
}

// ── Helpers ──

function getFillColor(fills?: OPFill[]): string {
  if (!fills || fills.length === 0) return 'none';
  const solid = fills.find(f => f.type === 'solid' && f.visible !== false);
  return solid?.color ?? 'none';
}

function getStrokeAttrs(strokes?: OPStroke[]): string {
  if (!strokes || strokes.length === 0) return '';
  const s = strokes[0];
  return ` stroke="${s.color}" stroke-width="${s.weight}"`;
}

function getFilterAttr(node: OPNode): string {
  if (!node.effects || node.effects.length === 0) return '';
  const shadow = node.effects.find(e => e.type === 'drop-shadow');
  if (shadow) return ` filter="url(#shadow-${node.id})"`;
  return '';
}

function collectFilters(nodes: OPNode[]): string[] {
  const filters: string[] = [];

  function walk(nodeList: OPNode[]) {
    for (const node of nodeList) {
      if (node.effects) {
        for (const effect of node.effects) {
          if (effect.type === 'drop-shadow') {
            const dx = effect.offset?.x ?? 0;
            const dy = effect.offset?.y ?? 4;
            const blur = effect.radius ?? 8;
            filters.push(
              `<filter id="shadow-${node.id}" x="-20%" y="-20%" width="140%" height="140%">` +
              `<feDropShadow dx="${dx}" dy="${dy}" stdDeviation="${blur / 2}" flood-color="${effect.color ?? '#00000020'}"/>` +
              `</filter>`,
            );
          }
        }
      }
      if (node.children) walk(node.children);
    }
  }

  walk(nodes);
  return filters;
}

function escapeHTML(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function escapeAttr(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ── ASCII rendering ──

function renderNodeASCII(node: OPNode, lines: string[], depth: number): void {
  const indent = '│ '.repeat(depth);
  const w = node.width ?? 0;
  const h = node.height ?? 0;
  const dims = w && h ? ` (${w}×${h})` : '';
  const typeLabel = node.type.toUpperCase().padEnd(10);

  if (node.type === 'text') {
    lines.push(`${indent}├─ ${typeLabel} "${node.characters ?? ''}"${dims}`);
  } else {
    lines.push(`${indent}├─ ${typeLabel} ${node.name ?? 'unnamed'}${dims}`);
  }

  if (node.children) {
    for (const child of node.children) {
      renderNodeASCII(child, lines, depth + 1);
    }
  }
}
